/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.FundsRetrieval;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.TrustFundOrg;
import Business.Role.TrustManagerRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FundingWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amityadav
 */
public class GovtFundingPanel extends javax.swing.JPanel {

    EcoSystem ecoSystem;
    Enterprise enterprise;
    Organization organization;
    JPanel panel;
    private UserAccount useraccount;
    String patient = null;
    
    /**
     * Creates new form GovtFundingPanel
     */
    public GovtFundingPanel(EcoSystem ecoSystem, Enterprise enterprise, Organization org, JPanel panel, UserAccount useraccount) {
        initComponents();
        this.ecoSystem = ecoSystem;
        this.enterprise = enterprise;
        this.organization = org;
        this.panel = panel;
        this.useraccount = useraccount;
        
        populateTable();
    }
    
    public void populateTable(){
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        trustEventFundRaisingDetailsTbl = new javax.swing.JTable();
        trustEventFundRaisingDetailsLbl = new javax.swing.JLabel();
        appointToMeBtn = new javax.swing.JButton();
        processBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        trustEventFundRaisingDetailsTbl.setBackground(java.awt.SystemColor.info);
        trustEventFundRaisingDetailsTbl.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        trustEventFundRaisingDetailsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status"
            }
        ));
        jScrollPane1.setViewportView(trustEventFundRaisingDetailsTbl);

        trustEventFundRaisingDetailsLbl.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        trustEventFundRaisingDetailsLbl.setText("Trust Event Fund Raising Details");

        appointToMeBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        appointToMeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/icons8-audit-24.png"))); // NOI18N
        appointToMeBtn.setText("Appoint To Me");
        appointToMeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointToMeBtnActionPerformed(evt);
            }
        });

        processBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        processBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/process.png"))); // NOI18N
        processBtn.setText("Process");
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/gvt funding panel gif.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trustEventFundRaisingDetailsLbl)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(appointToMeBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(processBtn))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)))
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel1)
                .addContainerGap(379, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(trustEventFundRaisingDetailsLbl)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointToMeBtn)
                    .addComponent(processBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void appointToMeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointToMeBtnActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_appointToMeBtnActionPerformed

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = trustEventFundRaisingDetailsTbl.getSelectedRow();

        if(trustEventFundRaisingDetailsTbl.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "No rows available to select", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        FundingWorkRequest request = (FundingWorkRequest)trustEventFundRaisingDetailsTbl.getValueAt(selectedRow, 0);
         if(request.getStatus().equalsIgnoreCase("Approved") || request.getStatus().equalsIgnoreCase("Declined")){
            JOptionPane.showMessageDialog(null, "The funds have alrady been Approved/Declined!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(request.getStatus().equalsIgnoreCase("Pending")){
        
            request.setFundStatus("Processing");
        
        FundsApprovalPanel processWorkRequestJPanel = new FundsApprovalPanel(panel, request, useraccount);
        panel.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) panel.getLayout();
        layout.next(panel);
        }else{
            JOptionPane.showMessageDialog(null, "Please assign the request first!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
    }//GEN-LAST:event_processBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointToMeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processBtn;
    private javax.swing.JLabel trustEventFundRaisingDetailsLbl;
    private javax.swing.JTable trustEventFundRaisingDetailsTbl;
    // End of variables declaration//GEN-END:variables
}
