/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.HospitalAdminWorkspace;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UI.CommonUI.ViewDonorValidationDashboard;
import UI.HospitalApplicant.RecipientRegistrationForm;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author amityadav
 */
public class ManageHospitalApplicant extends javax.swing.JPanel {

    /**
     * Creates new form ManageHospitalVisitors
     */
    JPanel rightJPanel;
    Organization org;
    Enterprise enterpriseObj;
    UserAccount account;

    public ManageHospitalApplicant(JPanel rightJPanel, Organization org, Enterprise enterpriseObj, UserAccount account) {
        initComponents();
        this.rightJPanel = rightJPanel;
        this.org = org;
        this.enterpriseObj = enterpriseObj;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donorBtn = new javax.swing.JButton();
        recipientBtn = new javax.swing.JButton();
        manageHospitalApplicantsLbl = new javax.swing.JLabel();
        DonorValidationRequestsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        donorBtn.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        donorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/icons8-donor-32.png"))); // NOI18N
        donorBtn.setText("Donor");
        donorBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        donorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorBtnActionPerformed(evt);
            }
        });
        add(donorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 262, 82));

        recipientBtn.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        recipientBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/icons8-welfare-32.png"))); // NOI18N
        recipientBtn.setText("Recipient");
        recipientBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        recipientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipientBtnActionPerformed(evt);
            }
        });
        add(recipientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 260, 82));

        manageHospitalApplicantsLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        manageHospitalApplicantsLbl.setText("Manage Hospital Applicants");
        add(manageHospitalApplicantsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        DonorValidationRequestsBtn.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        DonorValidationRequestsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/team-management.png"))); // NOI18N
        DonorValidationRequestsBtn.setText(" Donor Validation Requests");
        DonorValidationRequestsBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DonorValidationRequestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonorValidationRequestsBtnActionPerformed(evt);
            }
        });
        add(DonorValidationRequestsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 506, 82));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/hsop (1).jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 1, 1000, 670));
    }// </editor-fold>//GEN-END:initComponents

    private void donorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorBtnActionPerformed
        ShowingInterestUI interestObj = new ShowingInterestUI(rightJPanel, org, enterpriseObj,account);
        rightJPanel.add("manageInterest", interestObj);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_donorBtnActionPerformed

    private void recipientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipientBtnActionPerformed
        // TODO add your handling code here:
        RecipientRegistrationForm reciptObj = new RecipientRegistrationForm(org, rightJPanel);
        rightJPanel.add("recipientRegistrationForm", reciptObj);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_recipientBtnActionPerformed

    private void DonorValidationRequestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonorValidationRequestsBtnActionPerformed
        // TODO add your handling code here:
        ViewDonorValidationDashboard viewDonorDashboard = new ViewDonorValidationDashboard(rightJPanel, enterpriseObj);
        rightJPanel.add("viewDonorDashboard",viewDonorDashboard);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_DonorValidationRequestsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DonorValidationRequestsBtn;
    private javax.swing.JButton donorBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel manageHospitalApplicantsLbl;
    private javax.swing.JButton recipientBtn;
    // End of variables declaration//GEN-END:variables
}
