/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.HospitalAdminWorkspace;

import Business.Enterprise.Enterprise;
import Business.Entity.Applicant;
import Business.Entity.ApplicantDirectory;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Utils.Utils;
import UI.HospitalApplicant.DonorRegistrationForm;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author amityadav
 */
public class ShowingInterestUI extends javax.swing.JPanel {

    /**
     * Creates new form ManageShowingInterest
     */
    JPanel rightJPanel;
    Organization org;
    ApplicantDirectory appDir = new ApplicantDirectory();
    public static int countReject = 0;
    Enterprise enterpriseObj;
    UserAccount account;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showingAwarenessLbl = new javax.swing.JLabel();
        enterEmailTxtLbl = new javax.swing.JLabel();
        enterEmailTxt = new javax.swing.JTextField();
        yesRadioBtn = new javax.swing.JRadioButton();
        noRadioBtn = new javax.swing.JRadioButton();
        submitBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        wantToBeDonorLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showingAwarenessLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        showingAwarenessLbl.setText("Showing Awareness Of Organ Donation importance");
        add(showingAwarenessLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, 42));

        enterEmailTxtLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterEmailTxtLbl.setText("Enter email ID");
        add(enterEmailTxtLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        enterEmailTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(enterEmailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 270, -1));

        yesRadioBtn.setBackground(java.awt.SystemColor.controlLtHighlight);
        yesRadioBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        yesRadioBtn.setText("YES");
        yesRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesRadioBtnActionPerformed(evt);
            }
        });
        add(yesRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        noRadioBtn.setBackground(java.awt.SystemColor.controlLtHighlight);
        noRadioBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        noRadioBtn.setText("NO");
        noRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRadioBtnActionPerformed(evt);
            }
        });
        add(noRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        submitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/icons8-submit-resume-24.png"))); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 200, 60));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/left-arrow-in-circular-button-black-symbol-2.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 130, 40));

        wantToBeDonorLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        wantToBeDonorLbl.setText("Do you want to be a donor?");
        add(wantToBeDonorLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void yesRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesRadioBtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_yesRadioBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        
      

    }//GEN-LAST:event_submitBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        rightJPanel.remove(this);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.previous(rightJPanel);

    }//GEN-LAST:event_backBtnActionPerformed

    private void noRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noRadioBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField enterEmailTxt;
    private javax.swing.JLabel enterEmailTxtLbl;
    private javax.swing.JRadioButton noRadioBtn;
    private javax.swing.JLabel showingAwarenessLbl;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel wantToBeDonorLbl;
    private javax.swing.JRadioButton yesRadioBtn;
    // End of variables declaration//GEN-END:variables
}
