/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.LabAssistant;
import Business.Role.InternalLabAssistantRole;
import Business.Role.RadiologistRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.File;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.mail.Session;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.InternetAddress;
import javax.mail.Message;
import javax.mail.Transport;


/**
 *
 * @author shobhitha
 */
public class TestResultUploadPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestResultUploadPanel
     */
    JPanel rightPanel;
    LabTestWorkRequest labTestWorkRequest;
    UserAccount userAccount;

    public TestResultUploadPanel(JPanel rightPanel, LabTestWorkRequest labTestWorkRequest, UserAccount userAccount) {
        initComponents();
        this.rightPanel = rightPanel;
        this.labTestWorkRequest = labTestWorkRequest;
        this.userAccount = userAccount;
        patient.setText(labTestWorkRequest.getPatientName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientlbl = new javax.swing.JLabel();
        resultTxt = new javax.swing.JTextField();
        uploadBtn = new javax.swing.JButton();
        uploadBtnLbl = new javax.swing.JLabel();
        submitResultBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        fileUploadPathDisplayerLabel = new javax.swing.JLabel();
        resultTxtLbl = new javax.swing.JLabel();
        patient = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        patientlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        patientlbl.setText("Patient:");

        resultTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resultTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultTxtActionPerformed(evt);
            }
        });

        uploadBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uploadBtn.setText("Upload");
        uploadBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        uploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadBtnActionPerformed(evt);
            }
        });

        uploadBtnLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uploadBtnLbl.setText("Upload Result:");

        submitResultBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitResultBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/icons8-submit-resume-24.png"))); // NOI18N
        submitResultBtn.setText("Submit Result");
        submitResultBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitResultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitResultBtnActionPerformed(evt);
            }
        });

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/left-arrow-in-circular-button-black-symbol-2.png"))); // NOI18N
        backBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        resultTxtLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resultTxtLbl.setText("Result:");

        patient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        patient.setText("<Patient>");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/view camp details gif.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileUploadPathDisplayerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 539, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientlbl)
                            .addComponent(resultTxtLbl)
                            .addComponent(uploadBtnLbl))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uploadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patient)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(submitResultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(patientlbl)
                                    .addComponent(patient))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(resultTxtLbl)
                                    .addComponent(resultTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62)
                                .addComponent(uploadBtnLbl))
                            .addComponent(uploadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addComponent(submitResultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fileUploadPathDisplayerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(401, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void uploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBtnActionPerformed
        JFileChooser jFileChooserObject = new JFileChooser();
        jFileChooserObject.showOpenDialog(null);
        File f = jFileChooserObject.getSelectedFile();
        String fileToUpload = f.getAbsolutePath();
        fileUploadPathDisplayerLabel.setText(fileToUpload);
        labTestWorkRequest.setTestUploaded(fileToUpload);
    }//GEN-LAST:event_uploadBtnActionPerformed

    private void submitResultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitResultBtnActionPerformed
        if (resultTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter a comment!");
            return;
        } else {
            labTestWorkRequest.setTestResult(resultTxt.getText());
            boolean variableForSession = false;
            final String toPerson = labTestWorkRequest.getPatientId().trim(); 
            String from = "organdonationaed@gmail.com";
            String host = "smtp.gmail.com";
            String username = "organdonationaed@gmail.com";
            String password = "Pass@1234";
            Properties propertiesOfEmailServer = System.getProperties();
            propertiesOfEmailServer.setProperty("mail.smtp.host", host);
            propertiesOfEmailServer.put("mail.smtp.starttls.required", "true");
            propertiesOfEmailServer.put("mail.smtp.starttls.enable", "true");
            propertiesOfEmailServer.put("mail.smtp.host", host);
            propertiesOfEmailServer.put("mail.smtp.port", "587");
            propertiesOfEmailServer.put("mail.smtp.auth", "true");
            java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
            Session session;
            session = Session.getDefaultInstance(propertiesOfEmailServer, null);
            session.setDebug(variableForSession);
            try {
                MimeMessage messageToSendEmail = new MimeMessage(session);
                messageToSendEmail.setFrom(new InternetAddress(from));
                messageToSendEmail.setRecipient(Message.RecipientType.TO, new InternetAddress(toPerson));
                messageToSendEmail.setRecipient(Message.RecipientType.CC, new InternetAddress(labTestWorkRequest.getSender().getUsername()));
                InternetAddress addressToPerson;
                addressToPerson = new InternetAddress(toPerson);
                messageToSendEmail.setSubject("Your Test Report is ready!");
                messageToSendEmail.setText("Hello! You can find the report in Attachment.");
                messageToSendEmail.setFileName(labTestWorkRequest.getTestUploaded());
                Transport transport = session.getTransport("smtp");
                transport.connect(host, username, password);
                transport.sendMessage(messageToSendEmail, messageToSendEmail.getAllRecipients());
                transport.close();
            } catch (Exception e) {
                System.out.println(e);
            }
            labTestWorkRequest.setStatus("Completed");
            JOptionPane.showMessageDialog(null, "Reports Uploaded. Request processing completed.");
            resultTxt.setText("");
            submitResultBtn.setEnabled(false);
            uploadBtn.setEnabled(false);
        }
    }//GEN-LAST:event_submitResultBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        Component[] arrayOfComponents = rightPanel.getComponents();
        Component componentObject = arrayOfComponents[arrayOfComponents.length - 1];
        LabAssistantWorkAreaPanel labAssistantWorkAreaPanelObject = (LabAssistantWorkAreaPanel) componentObject;
        labAssistantWorkAreaPanelObject.methodToPopulateTableData();
//        if (userAccount.getRole() instanceof InternalLabAssistantRole) {
//            labAssistantWorkAreaPanelObject.methodToPopulateTableData();
//        } else if (userAccount.getRole() instanceof RadiologistRole) {
//            labAssistantWorkAreaPanelObject.methodToPopulateTableEnterprise();
//        }
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);

    }//GEN-LAST:event_backBtnActionPerformed

    private void resultTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel fileUploadPathDisplayerLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel patient;
    private javax.swing.JLabel patientlbl;
    private javax.swing.JTextField resultTxt;
    private javax.swing.JLabel resultTxtLbl;
    private javax.swing.JButton submitResultBtn;
    private javax.swing.JButton uploadBtn;
    private javax.swing.JLabel uploadBtnLbl;
    // End of variables declaration//GEN-END:variables
}
