/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.CommonUI;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Utils.Utils;
import UI.HospitalAdminWorkspace.ManageHospitalApplicant;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shobhitha
 */
public class ManageEmployeeReusablePanel extends javax.swing.JPanel {

    JPanel rightJPanel;
    private Enterprise enterpriseObj;

    /**
     * Creates new form ManageEmployeeReusablePanel
     */
    public ManageEmployeeReusablePanel(JPanel rightJPanel, Enterprise enterpriseObj) {
        initComponents();
        this.rightJPanel = rightJPanel;
        this.enterpriseObj = enterpriseObj;
        populateOrgDropDown();
        populateOrganizationEmpComboBox();
    }

    private void populateOrgDropDown() {
        filterDropdown.removeAllItems();
        for (Organization organization : enterpriseObj.getOrganizationDirectory().getOrganizationList()) {
            filterDropdown.addItem(organization);
        }
    }

    private void populateOrganizationEmpComboBox() {;
        orgEmployeeDropdown.removeAllItems();
        for (Organization organization : enterpriseObj.getOrganizationDirectory().getOrganizationList()) {
            orgEmployeeDropdown.addItem(organization);
        }
    }

    private void populateEmployeeTable(Organization org) {
        DefaultTableModel tableModel = (DefaultTableModel) manageEmplyeesTbl.getModel();
        tableModel.setRowCount(0);
        for (Employee employeeObj : org.getEmployeeDirectory().getEmpList()) {
            Object[] row = new Object[3];
            row[1] = employeeObj.getEmpID();
            row[2] = employeeObj.getEmpName();
            row[0] = org.getName();
            tableModel.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        manageEmplyeesTbl = new javax.swing.JTable();
        orgEmployeeDropdown = new javax.swing.JComboBox();
        nameTxt = new javax.swing.JTextField();
        nameLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        manageEmployeesLbl = new javax.swing.JLabel();
        filterDropdown = new javax.swing.JComboBox();
        organizationDropdownLbl = new javax.swing.JLabel();
        filterLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageEmplyeesTbl.setBackground(java.awt.SystemColor.info);
        manageEmplyeesTbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageEmplyeesTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Organization", "Employee Id", "Employee Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manageEmplyeesTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 960, 170));

        orgEmployeeDropdown.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        orgEmployeeDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        orgEmployeeDropdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                orgEmployeeDropdownMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                orgEmployeeDropdownMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orgEmployeeDropdownMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orgEmployeeDropdownMouseEntered(evt);
            }
        });
        orgEmployeeDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgEmployeeDropdownActionPerformed(evt);
            }
        });
        add(orgEmployeeDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 270, 40));

        nameTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 270, 40));

        nameLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameLbl.setText("Name:");
        add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        backBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/left-arrow-in-circular-button-black-symbol-2.png"))); // NOI18N
        backBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 40));

        addBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/icons8-plus-+-24.png"))); // NOI18N
        addBtn.setText("Add ");
        addBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 160, 40));

        manageEmployeesLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        manageEmployeesLbl.setText("Manage Employees");
        add(manageEmployeesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, 30));

        filterDropdown.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        filterDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filterDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterDropdownActionPerformed(evt);
            }
        });
        add(filterDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 160, -1));

        organizationDropdownLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        organizationDropdownLbl.setText("Organization:");
        add(organizationDropdownLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        filterLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        filterLbl.setText("View By Filter:");
        add(filterLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/working gif.gif"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, 450, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void orgEmployeeDropdownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orgEmployeeDropdownMouseClicked

    }//GEN-LAST:event_orgEmployeeDropdownMouseClicked

    private void orgEmployeeDropdownMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orgEmployeeDropdownMouseEntered

    }//GEN-LAST:event_orgEmployeeDropdownMouseEntered

    private void orgEmployeeDropdownMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orgEmployeeDropdownMousePressed

    }//GEN-LAST:event_orgEmployeeDropdownMousePressed

    private void orgEmployeeDropdownMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orgEmployeeDropdownMouseReleased

    }//GEN-LAST:event_orgEmployeeDropdownMouseReleased

    private void orgEmployeeDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgEmployeeDropdownActionPerformed

        nameTxt.setEnabled(true);
        nameTxt.setEditable(true);

    }//GEN-LAST:event_orgEmployeeDropdownActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        rightJPanel.remove(this);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.previous(rightJPanel);

    }//GEN-LAST:event_backBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        Utils util = new Utils();
        Organization org = (Organization) orgEmployeeDropdown.getSelectedItem();
        if ((!util.notNullOrEmpty(nameTxt.getText()) || !util.isValidName(nameTxt.getText()))) {
            JOptionPane.showMessageDialog(null, "Please enter valid name.");
            return;
        }
//       if (org.getName().equals("Applicant Org")) {
//            ManageHospitalApplicant hospitalApplicantScreen = new ManageHospitalApplicant(rightJPanel, org, enterpriseObj);
//            rightJPanel.add("hospitalApplicantScreen", hospitalApplicantScreen);
//            CardLayout layout = (CardLayout) rightJPanel.getLayout();
//            layout.next(rightJPanel);
//        } else {
        Employee e = org.getEmployeeDirectory().createEmployee(nameTxt.getText());
        JOptionPane.showMessageDialog(null, "Employee added successfully!");
//        }
        populateEmployeeTable(org);
        filterDropdown.setSelectedItem(org);
        nameTxt.setText("");
    }//GEN-LAST:event_addBtnActionPerformed

    private void filterDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterDropdownActionPerformed
        Organization org = (Organization) filterDropdown.getSelectedItem();
        if (org != null) {
            populateEmployeeTable(org);
        }
    }//GEN-LAST:event_filterDropdownActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox filterDropdown;
    private javax.swing.JLabel filterLbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manageEmployeesLbl;
    private javax.swing.JTable manageEmplyeesTbl;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JComboBox orgEmployeeDropdown;
    private javax.swing.JLabel organizationDropdownLbl;
    // End of variables declaration//GEN-END:variables
}
