/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.CommonUI;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.WorkQueue.DonorValidationWorkRequest;
import Business.WorkQueue.WorkRequest;
import UI.HospitalAdminWorkspace.ManageHospitalApplicant;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shobhitha
 */
public class ViewDonorValidationDashboard extends javax.swing.JPanel {

    /**
     * Creates new form ViewDonorValidationDashboard
     */
    EcoSystem system;
    Enterprise enterpriseObj;
    JPanel rightJPanel;
    
    public ViewDonorValidationDashboard(JPanel rightJPanel, Enterprise enterpriseObj ) {
        initComponents();
        this.rightJPanel = rightJPanel;
        this.enterpriseObj = enterpriseObj;
        populateDonorValidationReqTable();
    }
    
    void populateDonorValidationReqTable(){
        DefaultTableModel model = (DefaultTableModel) donorValidationTbl.getModel();
        int fitDonorCount = 0;
        int totalDonorCount = 0;
        model.setRowCount(0);
        for(WorkRequest obj : enterpriseObj.getWorkQueue().getWorkRequestList()){
            if(obj instanceof DonorValidationWorkRequest){
                DonorValidationWorkRequest finalobj = (DonorValidationWorkRequest) obj;
                Object[] row = new Object[5];
                row[0] = finalobj;
                row[1] = finalobj.getPatientId();
                row[2] = finalobj.getSender();
                row[3] = finalobj.getReceiver() == null ? "Unassigned" : finalobj.getReceiver();
                row[4] = finalobj.getStatus();
                model.addRow(row); 
                if("Donor Fit".equalsIgnoreCase(finalobj.getTestResult())){
                    fitDonorCount ++;
                }
                totalDonorCount++;
            }
        }
        totalDonorsValueLbl.setText(String.valueOf(totalDonorCount));
        totalFitDonorsValueLbl.setText(String.valueOf(fitDonorCount));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donorValidationWorkRequestsLbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        donorValidationTbl = new javax.swing.JTable();
        totlaFitDonorsLbl = new javax.swing.JLabel();
        totalDonorsLbl = new javax.swing.JLabel();
        totalDonorsValueLbl = new javax.swing.JLabel();
        totalFitDonorsValueLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        donorValidationWorkRequestsLbl.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        donorValidationWorkRequestsLbl.setText("Donor Validation Work Requests");

        donorValidationTbl.setBackground(java.awt.SystemColor.info);
        donorValidationTbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        donorValidationTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Donor Id", "Sender", "Receiver", "Status", "Test Results"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(donorValidationTbl);

        totlaFitDonorsLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totlaFitDonorsLbl.setText("Total Fit Donors: ");

        totalDonorsLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalDonorsLbl.setText("Total Donors: ");

        totalDonorsValueLbl.setBackground(new java.awt.Color(255, 255, 255));
        totalDonorsValueLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalDonorsValueLbl.setText("<totalDonrs>");

        totalFitDonorsValueLbl.setBackground(new java.awt.Color(255, 255, 255));
        totalFitDonorsValueLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalFitDonorsValueLbl.setText("<totalFitDonors>");

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/left-arrow-in-circular-button-black-symbol-2.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalDonorsLbl)
                    .addComponent(totalDonorsValueLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totlaFitDonorsLbl)
                    .addComponent(totalFitDonorsValueLbl))
                .addGap(559, 559, 559))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addComponent(donorValidationWorkRequestsLbl)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(469, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donorValidationWorkRequestsLbl))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalDonorsValueLbl)
                            .addComponent(totalFitDonorsValueLbl))
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totlaFitDonorsLbl)
                            .addComponent(totalDonorsLbl))))
                .addContainerGap(459, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        rightJPanel.remove(this);
        Component[] componentArray = rightJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageHospitalApplicant manageHospital = (ManageHospitalApplicant) component;
        CardLayout cardLayout = (CardLayout) rightJPanel.getLayout();
        cardLayout.previous(rightJPanel);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable donorValidationTbl;
    private javax.swing.JLabel donorValidationWorkRequestsLbl;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel totalDonorsLbl;
    private javax.swing.JLabel totalDonorsValueLbl;
    private javax.swing.JLabel totalFitDonorsValueLbl;
    private javax.swing.JLabel totlaFitDonorsLbl;
    // End of variables declaration//GEN-END:variables
}
