/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.FundsRetrieval;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.CorporateFundOrg;
import Business.Role.CorporateManagerRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FundingWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amityadav
 */
public class CorporateFundingPanel extends javax.swing.JPanel {

    EcoSystem ecoSystem;
    Enterprise enterprise;
    Organization organization;
    JPanel panel;
    private UserAccount useraccount;
    String patient = null;
    /**
     * Creates new form CorporateFundingPanel
     */
    public CorporateFundingPanel(EcoSystem ecoSystem, Enterprise enterprise, Organization org, JPanel panel, UserAccount useraccount) {
        initComponents();
        this.ecoSystem = ecoSystem;
        this.enterprise = enterprise;
        this.organization = org;
        this.panel = panel;
        this.useraccount = useraccount;
        populateTable();
    }
    
    public void populateTable(){

        DefaultTableModel dtm  = (DefaultTableModel)corporateEventFundRaisingDetailsTbl.getModel();
        dtm.setRowCount(0);
        
        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){  
            System.out.println(organization);
            System.out.println(organization.getWorkQueue().getWorkRequestList());
            if(organization instanceof CorporateFundOrg){
            for(WorkRequest req : organization.getWorkQueue().getWorkRequestList()){
                
            Object[] row = new Object[4];
            row[0] = req;
            row[1] = req.getSender().getEmployee();
            row[2] = req.getReceiver() == null ? null : req.getReceiver().getEmployee().getEmpName();
            row[3] = req.getStatus();
            System.out.println(row[1]);
            System.out.println(row[2]);
            System.out.println(row[3]);
            dtm.addRow(row);
            }
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        corporateEventFundRaisingDetailsTblLbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        corporateEventFundRaisingDetailsTbl = new javax.swing.JTable();
        appointToMeBtn = new javax.swing.JButton();
        processBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        corporateEventFundRaisingDetailsTblLbl.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        corporateEventFundRaisingDetailsTblLbl.setText("Corporate Event Fund Raising Details");

        corporateEventFundRaisingDetailsTbl.setBackground(java.awt.SystemColor.info);
        corporateEventFundRaisingDetailsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status"
            }
        ));
        jScrollPane3.setViewportView(corporateEventFundRaisingDetailsTbl);

        appointToMeBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        appointToMeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/icons8-audit-24.png"))); // NOI18N
        appointToMeBtn.setText("Appoint to me");
        appointToMeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointToMeBtnActionPerformed(evt);
            }
        });

        processBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        processBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/process.png"))); // NOI18N
        processBtn.setText("Process");
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/corporate funding panel gif.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(corporateEventFundRaisingDetailsTblLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(appointToMeBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(processBtn))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 993, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(corporateEventFundRaisingDetailsTblLbl)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointToMeBtn)
                    .addComponent(processBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void appointToMeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointToMeBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = corporateEventFundRaisingDetailsTbl.getSelectedRow();

        if(corporateEventFundRaisingDetailsTbl.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "No rows available to select", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        WorkRequest request = (WorkRequest)corporateEventFundRaisingDetailsTbl.getValueAt(selectedRow, 0);
         if(request.getStatus().equalsIgnoreCase("Approved") || request.getStatus().equalsIgnoreCase("Declined")){
            JOptionPane.showMessageDialog(null, "The funds have alrady been Approved/Declined!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(request.getStatus().equalsIgnoreCase("Pending")){
            JOptionPane.showMessageDialog(null, "Assigned Request cannot be assigned again!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        request.setReceiver(useraccount);
        request.setStatus("Pending");
        if(useraccount.getRole() instanceof CorporateManagerRole){
            populateTable();
        }
    }//GEN-LAST:event_appointToMeBtnActionPerformed

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = corporateEventFundRaisingDetailsTbl.getSelectedRow();

        if(corporateEventFundRaisingDetailsTbl.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "No rows available to select", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        FundingWorkRequest request = (FundingWorkRequest)corporateEventFundRaisingDetailsTbl.getValueAt(selectedRow, 0);
        if(request.getStatus().equalsIgnoreCase("Approved") || request.getStatus().equalsIgnoreCase("Declined")){
            JOptionPane.showMessageDialog(null, "The funds have alrady been Approved/Declined!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(request.getStatus().equalsIgnoreCase("Pending")){
            request.setFundStatus("Processing");
        
        FundsApprovalPanel processWorkRequestJPanel = new FundsApprovalPanel(panel, request, useraccount);
        panel.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) panel.getLayout();
        layout.next(panel);
        }else{
            JOptionPane.showMessageDialog(null, "Please assign the request first!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_processBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointToMeBtn;
    private javax.swing.JTable corporateEventFundRaisingDetailsTbl;
    private javax.swing.JLabel corporateEventFundRaisingDetailsTblLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton processBtn;
    // End of variables declaration//GEN-END:variables
}
