/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.FundsRetrieval;

import Business.Role.TrustManagerRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FundingWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;



/**
 *
 * @author amityadav
 */
public class FundsApprovalPanel extends javax.swing.JPanel {

    JPanel panel;
    FundingWorkRequest request;
    UserAccount account;
    /**
     * Creates new form NewJPanel
     */
    public FundsApprovalPanel(JPanel panel, FundingWorkRequest request, UserAccount account ) {
        initComponents();
        this.panel = panel;
        this.request = request;
        this.account = account;
        populateFundAmount();              
    }

    public void populateFundAmount(){
        requestedFundTxt.setText(String.valueOf(request.getAmount()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundRequestedLbl = new javax.swing.JLabel();
        requestedFundTxt = new javax.swing.JTextField();
        approveFundsRequestBtn = new javax.swing.JButton();
        declineFundsRequestBtn = new javax.swing.JButton();
        requestedFundCurrencyLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        fundRequestedLbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        fundRequestedLbl.setText("Fund Requested");

        requestedFundTxt.setEditable(false);
        requestedFundTxt.setEnabled(false);
        requestedFundTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestedFundTxtActionPerformed(evt);
            }
        });

        approveFundsRequestBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        approveFundsRequestBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/check.png"))); // NOI18N
        approveFundsRequestBtn.setText("Approve Funds Request");
        approveFundsRequestBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        approveFundsRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveFundsRequestBtnActionPerformed(evt);
            }
        });

        declineFundsRequestBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        declineFundsRequestBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/close.png"))); // NOI18N
        declineFundsRequestBtn.setText("Decline Funds Request");
        declineFundsRequestBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        declineFundsRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineFundsRequestBtnActionPerformed(evt);
            }
        });

        requestedFundCurrencyLbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        requestedFundCurrencyLbl.setText("$");

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/left-arrow-in-circular-button-black-symbol-2.png"))); // NOI18N
        backBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/gvt funding panel gif.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fundRequestedLbl)
                        .addGap(232, 232, 232))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(565, 565, 565)
                                .addComponent(approveFundsRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(declineFundsRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(requestedFundCurrencyLbl)
                        .addGap(18, 18, 18)
                        .addComponent(requestedFundTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(552, 552, 552))
            .addGroup(layout.createSequentialGroup()
                .addGap(678, 678, 678)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fundRequestedLbl)
                    .addComponent(requestedFundTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestedFundCurrencyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approveFundsRequestBtn)
                    .addComponent(declineFundsRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestedFundTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestedFundTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestedFundTxtActionPerformed

    private void approveFundsRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveFundsRequestBtnActionPerformed
        if(request.getStatus().equalsIgnoreCase("Approved") || request.getStatus().equalsIgnoreCase("Declined")){
            JOptionPane.showMessageDialog(null, "The funds have already been Approved/Declined");
            return;
        }
        
        if(requestedFundTxt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter a comment!");
            return;
        }
        else{
            
            try {
                emailApproved("amit3012yadav@gmail.com");


            } catch (Exception ex) {
                Logger.getLogger(FundsApprovalPanel.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error encountered while sending email");
            }
            request.setStatus("Approved");
            JOptionPane.showMessageDialog(null, "Your funds have been approved and email has been sent");
        }
                                                         
    }//GEN-LAST:event_approveFundsRequestBtnActionPerformed


    private void declineFundsRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineFundsRequestBtnActionPerformed
        // TODO add your handling code here:
        if(request.getStatus().equalsIgnoreCase("Approved") || request.getStatus().equalsIgnoreCase("Declined")){
            JOptionPane.showMessageDialog(null, "The funds have already been Approved/Declined");
            return;
        }
        
        if(requestedFundTxt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter a comment!");
            return;
        }
        else{
            try {
                emailDeclined("amit3012yadav@gmail.com");
            } catch (Exception ex) {
                Logger.getLogger(FundsApprovalPanel.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error encountered while sending email");
            }
            request.setStatus("Declined");
            JOptionPane.showMessageDialog(null, "Funds have been declined and email has been sent");
            
             
        

 
        
    }
        
    }//GEN-LAST:event_declineFundsRequestBtnActionPerformed
public static void emailDeclined (String recepient) throws Exception {
        System.out.println("Preparing to send email");
        Properties properties = new Properties ();
        properties.put ("mail.smtp.auth","true");
        properties.put ("mail.smtp.starttls.enable","true");
        properties.put ("mail.smtp.host" , "smtp.gmail.com");
        properties.put ("mail.smtp.port","587");
        String myAccountEmail = "derrickrose3012@gmail.com";
        String password = "vbfknvllsxyfxcrq";

        Session session = Session.getInstance (properties, new Authenticator () {
        @Override
            protected PasswordAuthentication getPasswordAuthentication () {
                return new PasswordAuthentication (myAccountEmail, password);
            }
            });
        Message message = prepareDeclineMessage (session, myAccountEmail, recepient);
        Transport.send (message);
        //System.out.println("Message sent successfully");
    }
    private static Message prepareDeclineMessage (Session session, String myAccountEmail, String recepient) {
        try{
            Message message = new MimeMessage (session);
            message.setFrom(new InternetAddress (myAccountEmail));
            message. setRecipient (Message.RecipientType.TO, new InternetAddress (recepient));
            message.setSubject("Funds declined");
            message. setText ("Sorry, your request has been declined");
        return message;
        } catch (Exception ex) {
//        Logger.getLogger(Emailcode.class.getName ()). log (Level.SEVERE, null, ex);
        }
        return null;
        }
    
    public static void emailApproved (String recepient) throws Exception {
        System.out.println("Preparing to send email");
        Properties properties = new Properties ();
        properties.put ("mail.smtp.auth","true");
        properties.put ("mail.smtp.starttls.enable","true");
        properties.put ("mail.smtp.host" , "smtp.gmail.com");
        properties.put ("mail.smtp.port","587");
        String myAccountEmail = "derrickrose3012@gmail.com";
        String password = "vbfknvllsxyfxcrq";

        Session session = Session.getInstance (properties, new Authenticator () {
        @Override
            protected PasswordAuthentication getPasswordAuthentication () {
                return new PasswordAuthentication (myAccountEmail, password);
            }
            });
        Message message = prepareMessage (session, myAccountEmail, recepient);
        Transport.send (message);
        //System.out.println("Message sent successfully");
    }
    private static Message prepareMessage (Session session, String myAccountEmail, String recepient) {
        try{
            Message message = new MimeMessage (session);
            message.setFrom(new InternetAddress (myAccountEmail));
            message. setRecipient (Message.RecipientType.TO, new InternetAddress (recepient));
            message.setSubject("Funds Approved");
            message. setText ("Congratulations, your request has been approved");
        return message;
        } catch (Exception ex) {
//        Logger.getLogger(Emailcode.class.getName ()). log (Level.SEVERE, null, ex);
        }
        return null;
        }
    
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        panel.remove(this);
        Component[] componentArray = panel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        GovtFundingPanel cont = (GovtFundingPanel) component;
        if(account.getRole() instanceof TrustManagerRole)
        cont.populateTable();       
        CardLayout layout = (CardLayout) panel.getLayout();
        layout.previous(panel);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveFundsRequestBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton declineFundsRequestBtn;
    private javax.swing.JLabel fundRequestedLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel requestedFundCurrencyLbl;
    private javax.swing.JTextField requestedFundTxt;
    // End of variables declaration//GEN-END:variables
}