/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.HospitalApplicant;

import Business.Enterprise.Enterprise;
import Business.Entity.Donor;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Utils.Utils;
import Business.WorkQueue.DonorValidationWorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author amityadav
 */
public class DonorRegistrationForm extends javax.swing.JPanel {

    /**
     * Creates new form DonorRegistrationForm
     */
    Organization org;
    String emailStr;
    JPanel rightJPanel;
    Enterprise enterpriseObj;
    UserAccount account;
    
    public DonorRegistrationForm(JPanel rightJPanel, Organization org, String emailStr, Enterprise enterpriseObj, UserAccount account) {
        initComponents();
        this.rightJPanel = rightJPanel;
        this.org = org;
        this.emailStr = emailStr;
        emailIdTxt.setText(emailStr);
        this.enterpriseObj = enterpriseObj;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        donorRegistrationFormLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        ageTxt = new javax.swing.JTextField();
        ageLbl = new javax.swing.JLabel();
        sexLbl = new javax.swing.JLabel();
        maleRadioBtn = new javax.swing.JRadioButton();
        femaleRadioBtn = new javax.swing.JRadioButton();
        bloodGroupDropdown = new javax.swing.JComboBox();
        bloodGroupDropdownLbl = new javax.swing.JLabel();
        contactNumberLbl = new javax.swing.JLabel();
        emailIdTxt = new javax.swing.JTextField();
        emailIdTxtLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTxt = new javax.swing.JTextArea();
        selectOrganToDonateLbl = new javax.swing.JLabel();
        corneasCheckBox = new javax.swing.JCheckBox();
        heartCheckBox = new javax.swing.JCheckBox();
        liverCheckBox = new javax.swing.JCheckBox();
        pancreasCheckBox = new javax.swing.JCheckBox();
        lungsCheckBox = new javax.swing.JCheckBox();
        kidneyCheckBox = new javax.swing.JCheckBox();
        organAvailbilityNoRadioBtn = new javax.swing.JRadioButton();
        organAvailbilityYesRadioBtn = new javax.swing.JRadioButton();
        organAvailableQuestionLbl = new javax.swing.JLabel();
        emergencyContactLbl = new javax.swing.JLabel();
        emergencyContactNameTxt = new javax.swing.JTextField();
        emergencyContactNumberTxt = new javax.swing.JTextField();
        emergencyContactTxtLbl = new javax.swing.JLabel();
        emergencyNameLbl = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        digitalSignatureTxt = new javax.swing.JTextField();
        digitalSignatureLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        contactNumberTxt = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(153, 204, 255));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/left-arrow-in-circular-button-black-symbol-2.png"))); // NOI18N
        backBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        donorRegistrationFormLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        donorRegistrationFormLbl.setText("Donor Registration Form");

        nameLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameLbl.setText("Name:");

        nameTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        ageTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        ageLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ageLbl.setText("Age:");

        sexLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sexLbl.setText("Sex:");

        maleRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        maleRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        maleRadioBtn.setText("Male");

        femaleRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        femaleRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        femaleRadioBtn.setText("Female");

        bloodGroupDropdown.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bloodGroupDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O-positive", "O-negative ", "A-positive", "A-negative", "B-positive", "B-negative", "AB-positive", "AB-negative" }));

        bloodGroupDropdownLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bloodGroupDropdownLbl.setText("Blood Group:");

        contactNumberLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        contactNumberLbl.setText("Contact Number:");

        emailIdTxt.setEditable(false);
        emailIdTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailIdTxt.setEnabled(false);
        emailIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIdTxtActionPerformed(evt);
            }
        });

        emailIdTxtLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailIdTxtLbl.setText("Email Id:");

        addressLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addressLbl.setText("Address:");

        addressTxt.setColumns(20);
        addressTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addressTxt.setRows(5);
        jScrollPane1.setViewportView(addressTxt);

        selectOrganToDonateLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        selectOrganToDonateLbl.setText("After I pass away, I'd wish to donate:");

        corneasCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        corneasCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        corneasCheckBox.setText("Corneas");

        heartCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        heartCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        heartCheckBox.setText("Heart");
        heartCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heartCheckBoxActionPerformed(evt);
            }
        });

        liverCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        liverCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        liverCheckBox.setText("Liver");
        liverCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liverCheckBoxActionPerformed(evt);
            }
        });

        pancreasCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        pancreasCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pancreasCheckBox.setText("Pancreas");

        lungsCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        lungsCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lungsCheckBox.setText("Lungs");

        kidneyCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        kidneyCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kidneyCheckBox.setText("Kidney");

        organAvailbilityNoRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        organAvailbilityNoRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        organAvailbilityNoRadioBtn.setText("NO");

        organAvailbilityYesRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        organAvailbilityYesRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        organAvailbilityYesRadioBtn.setText("Yes");

        organAvailableQuestionLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        organAvailableQuestionLbl.setText("Organ Available Now?");

        emergencyContactLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emergencyContactLbl.setText("In Emergency, Person of Contact");

        emergencyContactNameTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        emergencyContactNumberTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emergencyContactNumberTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyContactNumberTxtActionPerformed(evt);
            }
        });

        emergencyContactTxtLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emergencyContactTxtLbl.setText("Contact Number:");

        emergencyNameLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emergencyNameLbl.setText("Name:");

        registerBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        registerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/icons8-register-32.png"))); // NOI18N
        registerBtn.setText("Register");
        registerBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        digitalSignatureTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        digitalSignatureTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitalSignatureTxtActionPerformed(evt);
            }
        });

        digitalSignatureLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        digitalSignatureLbl.setText("Digital Signature:");

        contactNumberTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(contactNumberTxt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bloodGroupDropdownLbl)
                                .addGap(136, 136, 136)
                                .addComponent(bloodGroupDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(contactNumberLbl)
                                .addGap(124, 124, 124)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressLbl)
                                    .addComponent(emailIdTxtLbl))
                                .addGap(137, 137, 137)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(ageLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(nameLbl)
                                    .addGap(114, 114, 114)
                                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(emailIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(donorRegistrationFormLbl)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(331, 331, 331)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(organAvailableQuestionLbl)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(heartCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lungsCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(pancreasCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(corneasCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(liverCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(157, 157, 157)
                                                    .addComponent(kidneyCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(organAvailbilityYesRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(124, 124, 124)
                                                        .addComponent(organAvailbilityNoRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(emergencyNameLbl)
                                                        .addComponent(emergencyContactLbl)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(emergencyContactNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(emergencyContactNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(346, 346, 346)
                                        .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(253, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(femaleRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1010, 1010, 1010))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(sexLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maleRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1176, 1176, 1176))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(selectOrganToDonateLbl)
                        .addGap(426, 426, 426))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(emergencyContactTxtLbl)
                        .addGap(619, 619, 619))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(digitalSignatureLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(digitalSignatureTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donorRegistrationFormLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLbl))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageLbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(selectOrganToDonateLbl)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(liverCheckBox)
                            .addComponent(kidneyCheckBox))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pancreasCheckBox)
                            .addComponent(corneasCheckBox))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lungsCheckBox)
                            .addComponent(heartCheckBox))
                        .addGap(33, 33, 33)
                        .addComponent(organAvailableQuestionLbl)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(organAvailbilityYesRadioBtn)
                            .addComponent(organAvailbilityNoRadioBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(femaleRadioBtn)
                            .addComponent(maleRadioBtn)
                            .addComponent(sexLbl))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bloodGroupDropdownLbl)
                            .addComponent(bloodGroupDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contactNumberLbl)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(emergencyContactLbl)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailIdTxtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 28, Short.MAX_VALUE)
                        .addComponent(addressLbl)
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(digitalSignatureTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(digitalSignatureLbl))
                        .addGap(251, 251, 251))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(emergencyNameLbl)
                                        .addComponent(emergencyContactNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(emergencyContactNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emergencyContactTxtLbl))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        rightJPanel.remove(this);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.previous(rightJPanel);

    }//GEN-LAST:event_backBtnActionPerformed

    private void emailIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIdTxtActionPerformed

    private void emergencyContactNumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyContactNumberTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emergencyContactNumberTxtActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        String nameAdded = nameTxt.getText();
        String sexSelected = "";
        if (maleRadioBtn.isSelected() && femaleRadioBtn.isSelected()) {
            JOptionPane.showMessageDialog(null, "Please only one gender.");
            return;
        }
         if (organAvailbilityYesRadioBtn.isSelected() && organAvailbilityNoRadioBtn.isSelected()) {
             JOptionPane.showMessageDialog(null, "Please only one status of organ availability.");
            return;
        }
        
        if (maleRadioBtn.isSelected()) {
            sexSelected = maleRadioBtn.getText();
        }
        if (femaleRadioBtn.isSelected()) {
            sexSelected = femaleRadioBtn.getText();
        }
        Object bloodGroup = bloodGroupDropdown.getSelectedItem();
        String addressAdded = addressTxt.getText();
        String contactNo = contactNumberTxt.getText();
        String emergencyName = emergencyContactNameTxt.getText();
        String emergencyNum = emergencyContactNumberTxt.getText();
        boolean availableNow = false;
        String sign = digitalSignatureTxt.getText();
        if (organAvailbilityYesRadioBtn.isSelected()) {
            availableNow = true;
        } else if (organAvailbilityNoRadioBtn.isSelected()) {
            availableNow = false;
        }
        List<String> organs = new ArrayList<String>();
        if (corneasCheckBox.isSelected()) {
            organs.add(corneasCheckBox.getText());
        }
        if (heartCheckBox.isSelected()) {
            organs.add(heartCheckBox.getText());
        }
        if (kidneyCheckBox.isSelected()) {
            organs.add(kidneyCheckBox.getText());
        }
        if (lungsCheckBox.isSelected()) {
            organs.add(lungsCheckBox.getText());
        }
        if (liverCheckBox.isSelected()) {
            organs.add(liverCheckBox.getText());
        }
        if (pancreasCheckBox.isSelected()) {
            organs.add(pancreasCheckBox.getText());
        }
        if (!(organAvailbilityYesRadioBtn.isSelected() || organAvailbilityNoRadioBtn.isSelected())) {
            JOptionPane.showMessageDialog(null, "Please select whether Organ currently available.");
            return;
        }
        if (nameTxt.equals("") || sexSelected.equals("") || sign.equals("") || emergencyName.equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all the fields listed below.");
            return;
        }
        if (!(corneasCheckBox.isSelected() || heartCheckBox.isSelected() || kidneyCheckBox.isSelected()
                || lungsCheckBox.isSelected() || liverCheckBox.isSelected() || pancreasCheckBox.isSelected())) {
            JOptionPane.showMessageDialog(null, "Please select the prgan up for donation.");
            return;
        }
        int age = 0;
        try {
            age = Integer.parseInt(ageTxt.getText());
            if (age > 120 || age < 18) {
                JOptionPane.showMessageDialog(null, "Please enter correct age.");
                ageTxt.setText("");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter age as a numeric.");
            ageTxt.setText("");
            return;
        }
        Utils util = new Utils();
        if (!util.isValidName(nameAdded) || !util.isValidName(emergencyName) || !util.isValidName(sign)) {
            JOptionPane.showMessageDialog(null, "Please enter valid name.");
            return;
        }
        if (!util.isEmaildIdvalid(emailStr)) {
            JOptionPane.showMessageDialog(null, "Please enter a valid email.");
            return;
        }
        if (!util.isValidPhoneNum(contactNo) || !util.isValidPhoneNum(emergencyNum)) {
            JOptionPane.showMessageDialog(null, " Please enter a 10 digit valid phone number");
            return;
        }
        if (org != null && org.getDonorDirectory() != null) {
            Donor donor = org.getDonorDirectory().createDonor(nameAdded, age,addressAdded , (String) bloodGroup, contactNo,
                    sexSelected, sign, emailStr, emergencyName, emergencyNum, availableNow, organs);
            
            DonorValidationWorkRequest requestObj = new DonorValidationWorkRequest();
            requestObj.setSender(account);
            requestObj.setMessage("Please Validate Donor");
            requestObj.setPatientId(emailStr);
            requestObj.setStatus("Request Raised");
            requestObj.setDonorObj(donor);
            enterpriseObj.getWorkQueue().getWorkRequestList().add(requestObj);
            JOptionPane.showMessageDialog(null, "Thankyou for registering as a donor.");
            rightJPanel.remove(this);
            CardLayout layout = (CardLayout) rightJPanel.getLayout();
            layout.previous(rightJPanel);
            
            // raise a work request to doctor org to validate donor
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void digitalSignatureTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digitalSignatureTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_digitalSignatureTxtActionPerformed

    private void heartCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heartCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heartCheckBoxActionPerformed

    private void liverCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liverCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liverCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLbl;
    private javax.swing.JTextArea addressTxt;
    private javax.swing.JLabel ageLbl;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox bloodGroupDropdown;
    private javax.swing.JLabel bloodGroupDropdownLbl;
    private javax.swing.JLabel contactNumberLbl;
    private javax.swing.JTextPane contactNumberTxt;
    private javax.swing.JCheckBox corneasCheckBox;
    private javax.swing.JLabel digitalSignatureLbl;
    private javax.swing.JTextField digitalSignatureTxt;
    private javax.swing.JLabel donorRegistrationFormLbl;
    private javax.swing.JTextField emailIdTxt;
    private javax.swing.JLabel emailIdTxtLbl;
    private javax.swing.JLabel emergencyContactLbl;
    private javax.swing.JTextField emergencyContactNameTxt;
    private javax.swing.JTextField emergencyContactNumberTxt;
    private javax.swing.JLabel emergencyContactTxtLbl;
    private javax.swing.JLabel emergencyNameLbl;
    private javax.swing.JRadioButton femaleRadioBtn;
    private javax.swing.JCheckBox heartCheckBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox kidneyCheckBox;
    private javax.swing.JCheckBox liverCheckBox;
    private javax.swing.JCheckBox lungsCheckBox;
    private javax.swing.JRadioButton maleRadioBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel organAvailableQuestionLbl;
    private javax.swing.JRadioButton organAvailbilityNoRadioBtn;
    private javax.swing.JRadioButton organAvailbilityYesRadioBtn;
    private javax.swing.JCheckBox pancreasCheckBox;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel selectOrganToDonateLbl;
    private javax.swing.JLabel sexLbl;
    // End of variables declaration//GEN-END:variables
}
