/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.HospitalApplicant;

import Business.Organization.Organization;
import Business.Utils.Utils;
import java.awt.CardLayout;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author amityadav
 */
public class RecipientRegistrationForm extends javax.swing.JPanel {
    
    Organization organization;
    JPanel panel;
    Utils utils = new Utils();
    /**
     * Creates new form RecipientRegistrationForm
     */
    public RecipientRegistrationForm(Organization organization, JPanel panel ) {
        initComponents();
        this.organization = organization;
        this.panel = panel;
        populateRadio1();
        populateRadio2();
    }
    
    private void populateRadio1() {
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(maleRadioBtn);
        buttonGroup.add(femaleRadioBtn);
    }
    
    private void populateRadio2() {
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(lungRadiodBtn);
        buttonGroup.add(kidneyRadioBtn);
        buttonGroup.add(pancreasRadioBtn);
        buttonGroup.add(corneasRadioBtn);
        buttonGroup.add(liverRadioBtn);
        buttonGroup.add(heartRadioBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        recipientRegFormMainLbl = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        nameTxtLbl = new javax.swing.JLabel();
        ageTxtLbl = new javax.swing.JLabel();
        sexTxtLbl = new javax.swing.JLabel();
        maleRadioBtn = new javax.swing.JRadioButton();
        femaleRadioBtn = new javax.swing.JRadioButton();
        ageTxt = new javax.swing.JTextField();
        bloodGroupDropdown = new javax.swing.JComboBox();
        bloodGroupLbl = new javax.swing.JLabel();
        contactNumberTxtLbl = new javax.swing.JLabel();
        emailIdTxtLbl = new javax.swing.JLabel();
        emailIdTxt = new javax.swing.JTextField();
        contactNumberTxt = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        addressTxt = new javax.swing.JTextArea();
        addressTxtLbl = new javax.swing.JLabel();
        signatureTxtLbl = new javax.swing.JLabel();
        signatureTxt = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        liverRadioBtn = new javax.swing.JRadioButton();
        corneasRadioBtn = new javax.swing.JRadioButton();
        pancreasRadioBtn = new javax.swing.JRadioButton();
        lungRadiodBtn = new javax.swing.JRadioButton();
        kidneyRadioBtn = new javax.swing.JRadioButton();
        heartRadioBtn = new javax.swing.JRadioButton();
        selectOrganLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/left-arrow-in-circular-button-black-symbol-2.png"))); // NOI18N
        backBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        recipientRegFormMainLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        recipientRegFormMainLbl.setText("Organ Recipient Form");

        nameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        nameTxtLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameTxtLbl.setText("Name");

        ageTxtLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ageTxtLbl.setText("Age");

        sexTxtLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sexTxtLbl.setText("Sex");

        maleRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        maleRadioBtn.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        maleRadioBtn.setText("Male");

        femaleRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        femaleRadioBtn.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        femaleRadioBtn.setText("Female");

        ageTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        bloodGroupDropdown.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        bloodGroupDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O-positive", "O-negative ", "A-positive", "A-negative", "B-positive", "B-negative", "AB-positive", "AB-negative" }));

        bloodGroupLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bloodGroupLbl.setText("Blood Group");

        contactNumberTxtLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        contactNumberTxtLbl.setText("Contact Number");

        emailIdTxtLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailIdTxtLbl.setText("Email Id");

        emailIdTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        contactNumberTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        addressTxt.setColumns(20);
        addressTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressTxt.setRows(5);
        jScrollPane3.setViewportView(addressTxt);

        addressTxtLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addressTxtLbl.setText("Address");

        signatureTxtLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        signatureTxtLbl.setText("Signature");

        signatureTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        submitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/icons8-submit-resume-24.png"))); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        liverRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        liverRadioBtn.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        liverRadioBtn.setText("Liver");
        liverRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liverRadioBtnActionPerformed(evt);
            }
        });

        corneasRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        corneasRadioBtn.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        corneasRadioBtn.setText("Corneas");

        pancreasRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        pancreasRadioBtn.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        pancreasRadioBtn.setText("Pancreas");

        lungRadiodBtn.setBackground(new java.awt.Color(255, 255, 255));
        lungRadiodBtn.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        lungRadiodBtn.setText("Lung");

        kidneyRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        kidneyRadioBtn.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        kidneyRadioBtn.setText("Kidney");

        heartRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        heartRadioBtn.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        heartRadioBtn.setText("Heart");
        heartRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heartRadioBtnActionPerformed(evt);
            }
        });

        selectOrganLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        selectOrganLbl.setText("Which part needs to transplant");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(701, 701, 701))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameTxtLbl)
                                .addComponent(ageTxtLbl)
                                .addComponent(sexTxtLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bloodGroupLbl)
                                    .addComponent(contactNumberTxtLbl)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addressTxtLbl)
                                        .addComponent(emailIdTxtLbl))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(signatureTxtLbl)
                                        .addGap(3, 3, 3)))
                                .addGap(20, 20, 20)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bloodGroupDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(maleRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(327, 327, 327)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(liverRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(52, 52, 52)
                                                        .addComponent(kidneyRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(selectOrganLbl)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lungRadiodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(femaleRadioBtn)
                                                        .addGap(218, 218, 218)
                                                        .addComponent(pancreasRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(61, 61, 61)
                                                .addComponent(corneasRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(14, 14, 14))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(heartRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1))))
                            .addComponent(signatureTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(579, 579, 579)
                        .addComponent(recipientRegFormMainLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recipientRegFormMainLbl))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTxtLbl))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageTxtLbl)
                            .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexTxtLbl)
                            .addComponent(maleRadioBtn)
                            .addComponent(femaleRadioBtn))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bloodGroupDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloodGroupLbl))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(addressTxtLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(contactNumberTxtLbl)
                                    .addComponent(contactNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(emailIdTxtLbl)
                                    .addComponent(emailIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(signatureTxtLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(selectOrganLbl)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(liverRadioBtn)
                            .addComponent(kidneyRadioBtn))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pancreasRadioBtn)
                            .addComponent(corneasRadioBtn))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(heartRadioBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(signatureTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(lungRadiodBtn)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(60, 60, 60)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        panel.remove(this);
        CardLayout layout = (CardLayout) panel.getLayout();
        layout.previous(panel);                          
    }//GEN-LAST:event_backBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String gender = "";
        int age; 
        if (maleRadioBtn.isSelected() && femaleRadioBtn.isSelected()) {
             JOptionPane.showMessageDialog(null, "Please only one gender.");
            return;
        }
        if(maleRadioBtn.isSelected()){
            gender = maleRadioBtn.getText();
        }else{
            gender = femaleRadioBtn.getText();
        }            
        String nameOnForm = nameTxt.getText();
        String phone = contactNumberTxt.getText();
        String emailID = emailIdTxt.getText();
        String signature = signatureTxt.getText(); 
        
       if(nameOnForm.equals("") || 
               gender.equals("") || 
               signature.equals("") || 
               emailID.equals("") || 
               phone.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill all the details.");
            return;
        }    
         try{
            age =  Integer.parseInt(ageTxt.getText());          
            if(age > 80 || age < 18){
                JOptionPane.showMessageDialog(null , "Please enter correct age.");
                ageTxt.setText("");
                 return;
            }
           }
           catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null , "Please add correct age"); 
            ageTxt.setText("");
               return;
           }           
         //Check Name validity
        if(!utils.isValidName(nameOnForm) ){
            JOptionPane.showMessageDialog(null, "Please enter valid name.");
            return;
        }    else if (!utils.isValidSign(signature)){
             JOptionPane.showMessageDialog(null, "Please enter valid sign.");
            return;
        }    
        //check Phone number validity
        if(!utils.isValidPhoneNo(phone)){
            JOptionPane.showMessageDialog(null, " Invalid Phone No." + 
                "Should be 10 digit number between 0-9");
            return;
        }
        //check email ID validity
        if(!utils.isEmaildIdvalid(emailID)){
            JOptionPane.showMessageDialog(null, "PLease enter a valid email id");
            return;
        }    
        if(!(corneasRadioBtn.isSelected() || 
                kidneyRadioBtn.isSelected() ||
                liverRadioBtn.isSelected() ||
                heartRadioBtn.isSelected() ||
                lungRadiodBtn.isSelected() ||                 
                pancreasRadioBtn.isSelected())){
            JOptionPane.showMessageDialog(null, "Kindly select an organ for transplantation");
            return;
        }
            
        Object bloodGroup = bloodGroupDropdown.getSelectedItem();

            String addr = addressTxt.getText();
            String organType;            
            if(corneasRadioBtn.isSelected())
                organType = pancreasRadioBtn.getText();               
            else if(kidneyRadioBtn.isSelected())
                organType = kidneyRadioBtn.getText();
            else if(heartRadioBtn.isSelected())
                organType = heartRadioBtn.getText();               
            else if(lungRadiodBtn.isSelected())
                organType = lungRadiodBtn.getText();
            else if(liverRadioBtn.isSelected())
                organType = liverRadioBtn.getText();
            else 
                organType = corneasRadioBtn.getText();            
            if(organization != null && organization.getRecipientDirectory() != null){
                organization.getRecipientDirectory().createRecipient(nameOnForm, age, addr, 
                        phone,emailID, (String) bloodGroup, gender,
                        signature, organType);
                JOptionPane.showMessageDialog(null, "You have been registered successfully.");
                
                signatureTxt.setText("");
                nameTxt.setText("");
                addressTxt.setText("");
                ageTxt.setText("");
                emailIdTxt.setText("");
                contactNumberTxt.setText("");
                
                panel.remove(this);
                CardLayout layout = (CardLayout) panel.getLayout();
                layout.previous(panel);
            }

    }//GEN-LAST:event_submitBtnActionPerformed

    private void heartRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heartRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heartRadioBtnActionPerformed

    private void liverRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liverRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liverRadioBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressTxt;
    private javax.swing.JLabel addressTxtLbl;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JLabel ageTxtLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox bloodGroupDropdown;
    private javax.swing.JLabel bloodGroupLbl;
    private javax.swing.JTextField contactNumberTxt;
    private javax.swing.JLabel contactNumberTxtLbl;
    private javax.swing.JRadioButton corneasRadioBtn;
    private javax.swing.JTextField emailIdTxt;
    private javax.swing.JLabel emailIdTxtLbl;
    private javax.swing.JRadioButton femaleRadioBtn;
    private javax.swing.JRadioButton heartRadioBtn;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton kidneyRadioBtn;
    private javax.swing.JRadioButton liverRadioBtn;
    private javax.swing.JRadioButton lungRadiodBtn;
    private javax.swing.JRadioButton maleRadioBtn;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel nameTxtLbl;
    private javax.swing.JRadioButton pancreasRadioBtn;
    private javax.swing.JLabel recipientRegFormMainLbl;
    private javax.swing.JLabel selectOrganLbl;
    private javax.swing.JLabel sexTxtLbl;
    private javax.swing.JTextField signatureTxt;
    private javax.swing.JLabel signatureTxtLbl;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
