/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.DoctorWorkspace;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.LabEnterprise;
import Business.Entity.Donor;
import Business.Entity.Recipient;
import Business.Network.Network;
import Business.Organization.InternalLabOrg;
import Business.Organization.Organization;
import Business.Organization.PathologyOrg;
import Business.Organization.RadiologyOrg;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonorValidationWorkRequest;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author amityadav
 */
public class DoctorRequestPatientTestPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorRequestPatientTestPanel
     */
    JPanel rightJPanel;
    Enterprise enterprise;
    private UserAccount account;
    EcoSystem business;

    void populatePatientIdDropdown() {
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (Donor donorObj : org.getDonorDirectory().getDonorRecords()) {
                if (account.getUsername().equalsIgnoreCase(donorObj.getDocAssignedEmaild())) {
                    donorListDropdown.addItem(donorObj);
                }
            }
            for (Recipient rObj : org.getRecipientDirectory().getRecipientRecords()) {
                // validate if patient is not assigned to a doctor or assigned to the same doctor
                if (!rObj.isIsDocAssigned() || account.getUsername().equalsIgnoreCase(rObj.getDocAssignedEmaild())) {
                    patientListDropdown.addItem(rObj);
                }
            }
        }
    }

    public DoctorRequestPatientTestPanel(JPanel rightJPanel, Enterprise enterprise, UserAccount account, EcoSystem business) {
        initComponents();
        this.rightJPanel = rightJPanel;
        this.enterprise = enterprise;
        this.account = account;
        this.business = business;
        populatePatientIdDropdown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        askToTakeTestButton = new javax.swing.JButton();
        bloodTestCheckbox = new javax.swing.JCheckBox();
        cancerScreeningCheckbox = new javax.swing.JCheckBox();
        donorListLbl = new javax.swing.JLabel();
        patientListDropdown = new javax.swing.JComboBox();
        listofTestsLbl = new javax.swing.JLabel();
        chestXrayCheckbox = new javax.swing.JCheckBox();
        radiologicTestingCheckbox = new javax.swing.JCheckBox();
        gynecologicalScreeningCheckbox = new javax.swing.JCheckBox();
        checkDonorReportsBtn = new javax.swing.JButton();
        veiwTestResultsLbl = new javax.swing.JLabel();
        testSuggestionPanelLbl = new javax.swing.JLabel();
        donorListDropdown = new javax.swing.JComboBox();
        requestDonorTestBtn = new javax.swing.JButton();
        checkRecipientReportsBtn = new javax.swing.JButton();
        pathologyLabTestsLbl = new javax.swing.JLabel();
        localLabTestsLbl = new javax.swing.JLabel();
        radiologyLabTestsLbl = new javax.swing.JLabel();
        requestPatientTestBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        patientlistLbl = new javax.swing.JLabel();

        askToTakeTestButton.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        askToTakeTestButton.setText("Request Patient Test");
        askToTakeTestButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        askToTakeTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                askToTakeTestButtonActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(153, 204, 255));
        setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N

        bloodTestCheckbox.setBackground(new java.awt.Color(255, 255, 255));
        bloodTestCheckbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bloodTestCheckbox.setText("Blood Test");

        cancerScreeningCheckbox.setBackground(new java.awt.Color(255, 255, 255));
        cancerScreeningCheckbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancerScreeningCheckbox.setText("Cancer Screening");

        donorListLbl.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        donorListLbl.setText("Donor List");

        patientListDropdown.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        patientListDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientListDropdownActionPerformed(evt);
            }
        });

        listofTestsLbl.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        listofTestsLbl.setText("List Of Tests");

        chestXrayCheckbox.setBackground(new java.awt.Color(255, 255, 255));
        chestXrayCheckbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chestXrayCheckbox.setText("Chest X-Ray and EKG");
        chestXrayCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chestXrayCheckboxActionPerformed(evt);
            }
        });

        radiologicTestingCheckbox.setBackground(new java.awt.Color(255, 255, 255));
        radiologicTestingCheckbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radiologicTestingCheckbox.setText("Radiologic Testing");
        radiologicTestingCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiologicTestingCheckboxActionPerformed(evt);
            }
        });

        gynecologicalScreeningCheckbox.setBackground(new java.awt.Color(255, 255, 255));
        gynecologicalScreeningCheckbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gynecologicalScreeningCheckbox.setText("Gynecological screening");
        gynecologicalScreeningCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gynecologicalScreeningCheckboxActionPerformed(evt);
            }
        });

        checkDonorReportsBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkDonorReportsBtn.setText("Check Donor Reports");
        checkDonorReportsBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkDonorReportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDonorReportsBtnActionPerformed(evt);
            }
        });

        veiwTestResultsLbl.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        veiwTestResultsLbl.setText("View Test Results");

        testSuggestionPanelLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        testSuggestionPanelLbl.setText("Test Suggestion Panel");

        donorListDropdown.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        donorListDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorListDropdownActionPerformed(evt);
            }
        });

        requestDonorTestBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        requestDonorTestBtn.setText("Request Donor Test");
        requestDonorTestBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        requestDonorTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestDonorTestBtnActionPerformed(evt);
            }
        });

        checkRecipientReportsBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkRecipientReportsBtn.setText("Check Recipient Reports");
        checkRecipientReportsBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkRecipientReportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRecipientReportsBtnActionPerformed(evt);
            }
        });

        pathologyLabTestsLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pathologyLabTestsLbl.setText("Pathology Lab Tests");

        localLabTestsLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        localLabTestsLbl.setText("Local Lab Tests");

        radiologyLabTestsLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radiologyLabTestsLbl.setText("Radiology Lab Tests");

        requestPatientTestBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        requestPatientTestBtn.setText("Request Patient Test");
        requestPatientTestBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        requestPatientTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestPatientTestBtnActionPerformed(evt);
            }
        });

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/left-arrow-in-circular-button-black-symbol-2.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        patientlistLbl.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        patientlistLbl.setText("Patient List");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(586, 586, 586)
                        .addComponent(testSuggestionPanelLbl)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(494, 494, 494)
                        .addComponent(listofTestsLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 510, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(checkRecipientReportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(319, 319, 319))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(482, 482, 482)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patientlistLbl)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(localLabTestsLbl)
                                        .addGap(189, 189, 189)
                                        .addComponent(pathologyLabTestsLbl))
                                    .addComponent(patientListDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(donorListLbl)
                                    .addComponent(donorListDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(checkDonorReportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(radiologyLabTestsLbl)
                                .addComponent(cancerScreeningCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(radiologicTestingCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(580, 580, 580)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chestXrayCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bloodTestCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)
                                .addComponent(gynecologicalScreeningCheckbox)
                                .addGap(176, 176, 176)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(requestDonorTestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(requestPatientTestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(veiwTestResultsLbl)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testSuggestionPanelLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(patientlistLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(patientListDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(requestPatientTestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(donorListLbl)
                                .addGap(29, 29, 29)
                                .addComponent(donorListDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(requestDonorTestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(listofTestsLbl)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(radiologyLabTestsLbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pathologyLabTestsLbl)
                            .addComponent(localLabTestsLbl))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiologicTestingCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodTestCheckbox)
                    .addComponent(gynecologicalScreeningCheckbox))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancerScreeningCheckbox)
                    .addComponent(chestXrayCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(veiwTestResultsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkDonorReportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkRecipientReportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void askToTakeTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_askToTakeTestButtonActionPerformed
        if (!bloodTestCheckbox.isSelected() && !gynecologicalScreeningCheckbox.isSelected() && !cancerScreeningCheckbox.isSelected()
                && !radiologicTestingCheckbox.isSelected() && !chestXrayCheckbox.isSelected()) {
            JOptionPane.showMessageDialog(null, "Please advice some test!");
            return;
        }

        if (patientListDropdown.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(null, "No patient selected!");
            return;
        }
        Recipient r = (Recipient) patientListDropdown.getItemAt(patientListDropdown.getSelectedIndex());
        r.setIsDocAssigned(true);
        r.setDocAssignedEmaild(account.getUsername());
        if (bloodTestCheckbox.isSelected() || chestXrayCheckbox.isSelected()) {
            LabTestWorkRequest request = new LabTestWorkRequest();
            request.setStatus("Request Raised");
            request.setMessage("Blood Test, Xray Requested");
            request.setSender(account);
            request.setPatientName(r.getPersonName());
            request.setPatientId(r.getPersonEmailId());
            request.setPatientType("Patient");
            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof InternalLabOrg) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(request);
                account.getWorkQueue().getWorkRequestList().add(request);
            }
            JOptionPane.showMessageDialog(null, "A request has been sent to internal lab!");
        }
        if (gynecologicalScreeningCheckbox.isSelected()) {
            LabTestWorkRequest request = new LabTestWorkRequest();
            request.setSender(account);
            request.setMessage("Gynecological Tests Requested");
            request.setStatus("Request Raised");
            request.setPatientType("Patient");
            request.setPatientName(r.getPersonName());
            request.setPatientId(r.getPersonEmailId());
            Organization orgObj = null;
            for (Network networkObj : business.getNetworks()) {
                for (Enterprise eObj : networkObj.getEnterpriseDirectory().getEnterpriseList()) {
                    if (eObj instanceof LabEnterprise) {
                        for (Organization org : eObj.getOrganizationDirectory().getOrganizationList()) {
                            if (org instanceof PathologyOrg) {
                                orgObj = org;
                            }
                        }
                    }
                }
            }
            if (orgObj != null) {
                orgObj.getWorkQueue().getWorkRequestList().add(request);
                account.getWorkQueue().getWorkRequestList().add(request);
                JOptionPane.showMessageDialog(null, "A request has been sent to pathology lab!");
            }
        }
        if (cancerScreeningCheckbox.isSelected() || radiologicTestingCheckbox.isSelected()) {
            LabTestWorkRequest request = new LabTestWorkRequest();
            request.setStatus("Request Raised");
            request.setSender(account);
            request.setMessage("Radiology Screening Requested");
            request.setPatientName(r.getPersonName());
            request.setPatientId(r.getPersonEmailId());
            request.setPatientType("Patient");
            Organization orgObj = null;
            for (Network networkObj : business.getNetworks()) {
                for (Enterprise eObj : networkObj.getEnterpriseDirectory().getEnterpriseList()) {
                    if (eObj instanceof LabEnterprise) {
                        for (Organization org : eObj.getOrganizationDirectory().getOrganizationList()) {
                            if (org instanceof RadiologyOrg) {
                                orgObj = org;
                            }
                        }
                    }
                }
            }
            if (orgObj != null) {
                orgObj.getWorkQueue().getWorkRequestList().add(request);
                account.getWorkQueue().getWorkRequestList().add(request);
                JOptionPane.showMessageDialog(null, "A request has been sent to radiology lab!");
            }
        }
        chestXrayCheckbox.setSelected(false);
        radiologicTestingCheckbox.setSelected(false);
        gynecologicalScreeningCheckbox.setSelected(false);
        bloodTestCheckbox.setSelected(false);
        cancerScreeningCheckbox.setSelected(false);

    }//GEN-LAST:event_askToTakeTestButtonActionPerformed

    private void checkDonorReportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDonorReportsBtnActionPerformed
        List<String> testLists = new ArrayList<>();
        if (bloodTestCheckbox.isSelected()) {
            testLists.add("Yes");
        } else {
            testLists.add("No");
        }
        if (radiologicTestingCheckbox.isSelected()) {
            testLists.add("Yes");
        } else {
            testLists.add("No");
        }
        if (chestXrayCheckbox.isSelected()) {
            testLists.add("Yes");
        } else {
            testLists.add("No");
        }
        String patientId = ((Donor) donorListDropdown.getItemAt(donorListDropdown.getSelectedIndex())).getPersonEmailId();
        ActivityAreaForDoctorPanel doctorActivityArea = new ActivityAreaForDoctorPanel(rightJPanel, account, enterprise, patientId, testLists, "Donor");
        rightJPanel.add("ActivityScreenForDoctor", doctorActivityArea);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);

    }//GEN-LAST:event_checkDonorReportsBtnActionPerformed

    private void chestXrayCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chestXrayCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chestXrayCheckboxActionPerformed

    private void requestDonorTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestDonorTestBtnActionPerformed
        // TODO add your handling code here:
        if (!bloodTestCheckbox.isSelected() && !gynecologicalScreeningCheckbox.isSelected() && !cancerScreeningCheckbox.isSelected()
                && !radiologicTestingCheckbox.isSelected() && !chestXrayCheckbox.isSelected()) {
            JOptionPane.showMessageDialog(null, "Please advice some test!");
            return;
        }
        if (donorListDropdown.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(null, "No donor selected!");
            return;
        }

        Donor r = (Donor) donorListDropdown.getItemAt(donorListDropdown.getSelectedIndex());
        r.setIsDocAssigned(true);
        r.setDocAssignedEmaild(account.getUsername());
        if (bloodTestCheckbox.isSelected() || chestXrayCheckbox.isSelected()) {
            LabTestWorkRequest request = new LabTestWorkRequest();
            request.setStatus("Request Raised");
            request.setMessage("Blood Test, Xray Requested");
            request.setSender(account);
            request.setPatientName(r.getPersonName());
            request.setPatientId(r.getPersonEmailId());
            request.setPatientType("Donor");
            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof InternalLabOrg) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(request);
                account.getWorkQueue().getWorkRequestList().add(request);
                JOptionPane.showMessageDialog(null, "A request has been sent to internal lab!");
            }

        }
        if (gynecologicalScreeningCheckbox.isSelected()) {
            LabTestWorkRequest request = new LabTestWorkRequest();
            request.setSender(account);
            request.setMessage("Gynecological Tests Requested");
            request.setStatus("Request Raised");
            request.setPatientName(r.getPersonName());
            request.setPatientId(r.getPersonEmailId());
            request.setPatientType("Donor");
            Organization orgObj = null;
            for (Network networkObj : business.getNetworks()) {
                for (Enterprise eObj : networkObj.getEnterpriseDirectory().getEnterpriseList()) {
                    if (eObj instanceof LabEnterprise) {
                        for (Organization org : eObj.getOrganizationDirectory().getOrganizationList()) {
                            if (org instanceof PathologyOrg) {
                                orgObj = org;
                            }
                        }
                    }
                }
            }
            if (orgObj != null) {
                orgObj.getWorkQueue().getWorkRequestList().add(request);
                account.getWorkQueue().getWorkRequestList().add(request);
                JOptionPane.showMessageDialog(null, "A request has been sent to pathology lab!");
                System.out.println("Creating A Request For Pathology Lab For Patient:" + request.getPatientId());
            }
        }
        if (cancerScreeningCheckbox.isSelected() || radiologicTestingCheckbox.isSelected()) {
            LabTestWorkRequest request = new LabTestWorkRequest();
            request.setStatus("Request Raised");
            request.setSender(account);
            request.setMessage("Requesting all screening for patient");
            request.setPatientType("Donor");
            request.setPatientName(r.getPersonName());
            request.setPatientId(r.getPersonEmailId());
            Organization orgObj = null;
            for (Network networkObj : business.getNetworks()) {
                for (Enterprise eObj : networkObj.getEnterpriseDirectory().getEnterpriseList()) {
                    if (eObj instanceof LabEnterprise) {
                        for (Organization org : eObj.getOrganizationDirectory().getOrganizationList()) {
                            if (org instanceof RadiologyOrg) {
                                orgObj = org;
                            }
                        }
                    }
                }
            }
            if (orgObj != null) {
                orgObj.getWorkQueue().getWorkRequestList().add(request);
                account.getWorkQueue().getWorkRequestList().add(request);
                JOptionPane.showMessageDialog(null, "A request has been sent to radiology lab!");
            }
//            int count = 0;
            for (WorkRequest w : enterprise.getWorkQueue().getWorkRequestList()) {
                if (w instanceof DonorValidationWorkRequest) {
                    DonorValidationWorkRequest a = (DonorValidationWorkRequest) w;
                    if (r.getPersonEmailId().equalsIgnoreCase(a.getPatientId())) {
                        a.setStatus("Requested Lab Tests");
                    }
                }
            }
//            if (count == 0) {
//                {
//                    DonorValidationWorkRequest validationRequest = new DonorValidationWorkRequest();
//                    Donor d = (Donor) donorComboName.getItemAt(donorComboName.getSelectedIndex());
//                    validationRequest.setStatus("Validation In Progress");
//                    validationRequest.setMessage("Awaiting Test Results");
//                    validationRequest.setSender(account);
//                    validationRequest.setReceiverName(enterprise.getName());
//                    validationRequest.setPatientName(d.getPersonName());
//                    validationRequest.setPatientId(d.getPersonEmailId());
//                    if (enterprise != null) {
//                        enterprise.getWorkQueue().getWorkRequestList().add(validationRequest);
//                        account.getWorkQueue().getWorkRequestList().add(validationRequest);
//                    }
//                }
//            }
        }
        chestXrayCheckbox.setSelected(false);
        radiologicTestingCheckbox.setSelected(false);
        gynecologicalScreeningCheckbox.setSelected(false);
        bloodTestCheckbox.setSelected(false);
        cancerScreeningCheckbox.setSelected(false);
    }//GEN-LAST:event_requestDonorTestBtnActionPerformed

    private void checkRecipientReportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRecipientReportsBtnActionPerformed
        // TODO add your handling code here:
        List<String> testLists = new ArrayList<>();
        if (bloodTestCheckbox.isSelected()) {
            testLists.add("Yes");
        } else {
            testLists.add("No");
        }
        if (radiologicTestingCheckbox.isSelected()) {
            testLists.add("Yes");
        } else {
            testLists.add("No");
        }
        if (chestXrayCheckbox.isSelected()) {
            testLists.add("Yes");
        } else {
            testLists.add("No");
        }
        Recipient patient = (Recipient) patientListDropdown.getItemAt(patientListDropdown.getSelectedIndex());
        String patientId = patient.getPersonEmailId();
        ActivityAreaForDoctorPanel doctorActivityArea = new ActivityAreaForDoctorPanel(rightJPanel, account, enterprise, patientId, testLists, "Patient");
        rightJPanel.add("ActivityScreenForDoctor", doctorActivityArea);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_checkRecipientReportsBtnActionPerformed

    private void patientListDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientListDropdownActionPerformed
        // TODO add your handling code here: 

    }//GEN-LAST:event_patientListDropdownActionPerformed

    private void gynecologicalScreeningCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gynecologicalScreeningCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gynecologicalScreeningCheckboxActionPerformed

    private void radiologicTestingCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiologicTestingCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiologicTestingCheckboxActionPerformed

    private void requestPatientTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestPatientTestBtnActionPerformed
        // TODO add your handling code here:
        if (!bloodTestCheckbox.isSelected() && !gynecologicalScreeningCheckbox.isSelected() && !cancerScreeningCheckbox.isSelected()
                && !radiologicTestingCheckbox.isSelected() && !chestXrayCheckbox.isSelected()) {
            JOptionPane.showMessageDialog(null, "Please advice some test!");
            return;
        }
        Recipient r = (Recipient) patientListDropdown.getItemAt(patientListDropdown.getSelectedIndex());
        r.setIsDocAssigned(true);
        r.setDocAssignedEmaild(account.getUsername());
        if (bloodTestCheckbox.isSelected() || chestXrayCheckbox.isSelected()) {
            LabTestWorkRequest request = new LabTestWorkRequest();
            request.setStatus("Request Raised");
            request.setMessage("Blood Test, Xray Requested");
            request.setSender(account);
            request.setPatientName(r.getPersonName());
            request.setPatientId(r.getPersonEmailId());
            request.setPatientType("Patient");
            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof InternalLabOrg) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(request);
                account.getWorkQueue().getWorkRequestList().add(request);
                JOptionPane.showMessageDialog(null, "A request has been sent to internal lab!");
            }

        }
        if (gynecologicalScreeningCheckbox.isSelected()) {
            LabTestWorkRequest request = new LabTestWorkRequest();
            request.setSender(account);
            request.setMessage("Gynecological Tests Requested");
            request.setStatus("Request Raised");
            request.setPatientType("Patient");
            request.setPatientName(r.getPersonName());
            request.setPatientId(r.getPersonEmailId());
            Organization orgObj = null;
            for (Network networkObj : business.getNetworks()) {
                for (Enterprise eObj : networkObj.getEnterpriseDirectory().getEnterpriseList()) {
                    if (eObj instanceof LabEnterprise) {
                        for (Organization org : eObj.getOrganizationDirectory().getOrganizationList()) {
                            if (org instanceof PathologyOrg) {
                                orgObj = org;
                            }
                        }
                    }
                }
            }
            if (orgObj != null) {
                orgObj.getWorkQueue().getWorkRequestList().add(request);
                account.getWorkQueue().getWorkRequestList().add(request);
                JOptionPane.showMessageDialog(null, "A request has been sent to pathology lab!");
            }
        }
        if (cancerScreeningCheckbox.isSelected() || radiologicTestingCheckbox.isSelected()) {
            LabTestWorkRequest request = new LabTestWorkRequest();
            request.setStatus("Request Raised");
            request.setSender(account);
            request.setMessage("Radiology Screening Requested");
            request.setPatientName(r.getPersonName());
            request.setPatientId(r.getPersonEmailId());
            request.setPatientType("Patient");
            Organization orgObj = null;
            for (Network networkObj : business.getNetworks()) {
                for (Enterprise eObj : networkObj.getEnterpriseDirectory().getEnterpriseList()) {
                    if (eObj instanceof LabEnterprise) {
                        for (Organization org : eObj.getOrganizationDirectory().getOrganizationList()) {
                            if (org instanceof RadiologyOrg) {
                                orgObj = org;
                            }
                        }
                    }
                }
            }
            if (orgObj != null) {
                orgObj.getWorkQueue().getWorkRequestList().add(request);
                account.getWorkQueue().getWorkRequestList().add(request);
                JOptionPane.showMessageDialog(null, "A request has been sent to radiology lab!");
            }
        }
        chestXrayCheckbox.setSelected(false);
        radiologicTestingCheckbox.setSelected(false);
        gynecologicalScreeningCheckbox.setSelected(false);
        bloodTestCheckbox.setSelected(false);
        cancerScreeningCheckbox.setSelected(false);
    }//GEN-LAST:event_requestPatientTestBtnActionPerformed

    private void donorListDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorListDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donorListDropdownActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        rightJPanel.remove(this);
        Component[] componentArray = rightJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout cardLayout = (CardLayout) rightJPanel.getLayout();
        cardLayout.previous(rightJPanel);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton askToTakeTestButton;
    private javax.swing.JButton backBtn;
    private javax.swing.JCheckBox bloodTestCheckbox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cancerScreeningCheckbox;
    private javax.swing.JButton checkDonorReportsBtn;
    private javax.swing.JButton checkRecipientReportsBtn;
    private javax.swing.JCheckBox chestXrayCheckbox;
    private javax.swing.JComboBox donorListDropdown;
    private javax.swing.JLabel donorListLbl;
    private javax.swing.JCheckBox gynecologicalScreeningCheckbox;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel listofTestsLbl;
    private javax.swing.JLabel localLabTestsLbl;
    private javax.swing.JLabel pathologyLabTestsLbl;
    private javax.swing.JComboBox patientListDropdown;
    private javax.swing.JLabel patientlistLbl;
    private javax.swing.JCheckBox radiologicTestingCheckbox;
    private javax.swing.JLabel radiologyLabTestsLbl;
    private javax.swing.JButton requestDonorTestBtn;
    private javax.swing.JButton requestPatientTestBtn;
    private javax.swing.JLabel testSuggestionPanelLbl;
    private javax.swing.JLabel veiwTestResultsLbl;
    // End of variables declaration//GEN-END:variables
}
