/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.DoctorWorkspace;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Entity.Donor;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonorValidationWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amityadav
 */
public class DoctorMainPage extends javax.swing.JPanel {

    /**
     * Creates new form DoctorMainPage
     */
    JPanel rightJPanel;
    Enterprise enterprise;
    UserAccount account;
    EcoSystem business;
    
    public DoctorMainPage(JPanel rightJPanel, Enterprise enterprise, UserAccount account, EcoSystem business) {
        initComponents();
        this.rightJPanel = rightJPanel;
        this.enterprise = enterprise;
        this.account = account;
        this.business = business;
        populateDonorValidationReqTable();
        doctorNameLbl.setText(account.getEmployee().getEmpName());
    }
    
    void populateDonorValidationReqTable(){
        DefaultTableModel model = (DefaultTableModel) donorValidationWorkRequestsTbl.getModel();
        model.setRowCount(0);
        for(WorkRequest obj : enterprise.getWorkQueue().getWorkRequestList()){
            if(obj instanceof DonorValidationWorkRequest && (obj.getReceiver() == null || obj.getReceiver() == account)){
                DonorValidationWorkRequest finalobj = (DonorValidationWorkRequest) obj;
                Object[] row = new Object[6];
                row[0] = finalobj;
                row[1] = finalobj.getPatientId();
                row[2] = finalobj.getSender();
                row[3] = finalobj.getReceiver() == null ? "Unassigned" : finalobj.getReceiver();
                row[4] = finalobj.getStatus();
                row[5] = finalobj.getTestResult();
                model.addRow(row); 
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appointRequestToMeBtn = new javax.swing.JButton();
        doctorMainPageLbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        donorValidationWorkRequestsTbl = new javax.swing.JTable();
        donorValidationWorkRequestsLbl = new javax.swing.JLabel();
        doctorNameLbl = new javax.swing.JLabel();
        testingAreaBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        appointRequestToMeBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        appointRequestToMeBtn.setText("Appoint Request To Me");
        appointRequestToMeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointRequestToMeBtnActionPerformed(evt);
            }
        });

        doctorMainPageLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        doctorMainPageLbl.setText("Doctor Main Page");

        donorValidationWorkRequestsTbl.setBackground(java.awt.SystemColor.info);
        donorValidationWorkRequestsTbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        donorValidationWorkRequestsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Donor Id", "Sender", "Receiver", "Status", "Test Results"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(donorValidationWorkRequestsTbl);
        donorValidationWorkRequestsTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        donorValidationWorkRequestsLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        donorValidationWorkRequestsLbl.setText("Donor Validation Work Requests");

        doctorNameLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        doctorNameLbl.setText("<DoctorName>");

        testingAreaBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        testingAreaBtn.setText(" Testing Area");
        testingAreaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testingAreaBtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/doc.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doctorMainPageLbl)
                .addGap(281, 281, 281)
                .addComponent(doctorNameLbl)
                .addGap(532, 532, 532))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(appointRequestToMeBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(testingAreaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(donorValidationWorkRequestsLbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(584, 584, 584)
                        .addComponent(jLabel1)))
                .addContainerGap(587, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(doctorNameLbl)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(doctorMainPageLbl)))
                .addGap(56, 56, 56)
                .addComponent(donorValidationWorkRequestsLbl)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointRequestToMeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testingAreaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void appointRequestToMeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointRequestToMeBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowOfTable = donorValidationWorkRequestsTbl.getSelectedRow();
        if (selectedRowOfTable < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to assign to yourself.", "INFO", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        DonorValidationWorkRequest wk = (DonorValidationWorkRequest)donorValidationWorkRequestsTbl.getValueAt(selectedRowOfTable, 0);
        if(wk.getStatus().equalsIgnoreCase("Request Raised")){
            if(wk.getReceiver() == null){
                wk.setReceiver(account);
                wk.setStatus("Request Processing");
                Donor donorObj = wk.getDonorObj();
                donorObj.setDocAssignedEmaild(account.getUsername());
                donorObj.setIsDocAssigned(true);
                // refresh validation request table
                populateDonorValidationReqTable();
                JOptionPane.showMessageDialog(null, "Donor assigned to you for validation", "INFO", JOptionPane.INFORMATION_MESSAGE);
            }
        }else {
                JOptionPane.showMessageDialog(null, "Request already in process", "INFO", JOptionPane.INFORMATION_MESSAGE);
                return;
        }
    }//GEN-LAST:event_appointRequestToMeBtnActionPerformed

    private void testingAreaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testingAreaBtnActionPerformed
        // TODO add your handling code here:
        DoctorRequestPatientTestPanel dbObj = new DoctorRequestPatientTestPanel(rightJPanel, enterprise, account, business);
        rightJPanel.add("doctorActivity", dbObj);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_testingAreaBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointRequestToMeBtn;
    private javax.swing.JLabel doctorMainPageLbl;
    private javax.swing.JLabel doctorNameLbl;
    private javax.swing.JLabel donorValidationWorkRequestsLbl;
    private javax.swing.JTable donorValidationWorkRequestsTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton testingAreaBtn;
    // End of variables declaration//GEN-END:variables
}
