/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SystemAdminWorkspace;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Utils.Utils;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shobhitha
 */
public class ManageEnterpriseAddEnterprise extends javax.swing.JPanel {

    EcoSystem ecoSystem;
    JPanel rightJPanel;

    /**
     * Creates new form ManageEnterpriseAddEnterprise
     */
    public ManageEnterpriseAddEnterprise(JPanel rightJPanel, EcoSystem ecosystemObj) {
        initComponents();
        this.ecoSystem = ecosystemObj;
        this.rightJPanel = rightJPanel;
        populateTable();
        populateComboBox();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) manageEnterpriseTbl.getModel();
        model.setRowCount(0);

        for (Network network : ecoSystem.getNetworks()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                Object[] row = new Object[3];
                row[0] = network.getName();
                row[1] = enterprise.getName();
                row[2] = enterprise.getEnterpriseType().getValue();
                model.addRow(row);
            }
        }
    }

    // populate filters
    private void populateComboBox() {
        cityDropdown.removeAllItems();
        for (Network city : ecoSystem.getNetworks()) {
            cityDropdown.addItem(city);
        }
        enterpriseTypeDropdown.removeAllItems();
        for (Enterprise.EnterpriseType enterpriseType : Enterprise.EnterpriseType.values()) {
            enterpriseTypeDropdown.addItem(enterpriseType);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jscrollPane = new javax.swing.JScrollPane();
        manageEnterpriseTbl = new javax.swing.JTable();
        cityLbl = new javax.swing.JLabel();
        enterpriseTypeLbl = new javax.swing.JLabel();
        enterpriseNameLbl = new javax.swing.JLabel();
        cityDropdown = new javax.swing.JComboBox();
        enterpriseTypeDropdown = new javax.swing.JComboBox();
        enterpriseNameTxt = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        manageEnterprisesLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageEnterpriseTbl.setBackground(java.awt.SystemColor.info);
        manageEnterpriseTbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageEnterpriseTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Network Name", "Enterprise Name", "Enterprise Type"
            }
        ));
        jscrollPane.setViewportView(manageEnterpriseTbl);

        add(jscrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 970, 170));

        cityLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cityLbl.setText("City");
        add(cityLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, -1));

        enterpriseTypeLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseTypeLbl.setText("Enterprise Type");
        add(enterpriseTypeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, -1, 20));

        enterpriseNameLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseNameLbl.setText("Enterprise Name");
        add(enterpriseNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, -1, -1));

        cityDropdown.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cityDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cityDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityDropdownActionPerformed(evt);
            }
        });
        add(cityDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 200, -1));

        enterpriseTypeDropdown.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterpriseTypeDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enterpriseTypeDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseTypeDropdownActionPerformed(evt);
            }
        });
        add(enterpriseTypeDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 200, -1));

        enterpriseNameTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterpriseNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseNameTxtActionPerformed(evt);
            }
        });
        add(enterpriseNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 200, -1));

        backBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/left-arrow-in-circular-button-black-symbol-2.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 120, 40));

        submitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/icons8-submit-resume-24.png"))); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, 150, 40));

        manageEnterprisesLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        manageEnterprisesLbl.setText("Manage Enterprises");
        add(manageEnterprisesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/Picture3.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 520, 410));
    }// </editor-fold>//GEN-END:initComponents

    private void enterpriseTypeDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseTypeDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseTypeDropdownActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        Utils util = new Utils();
        Enterprise.EnterpriseType enterpriseType = (Enterprise.EnterpriseType) enterpriseTypeDropdown.getSelectedItem();
        Network networkObj = (Network) cityDropdown.getSelectedItem();
        String enterpriseName = enterpriseNameTxt.getText();
        if (networkObj == null || enterpriseType == null) {
            JOptionPane.showMessageDialog(null, "Please select a network and enterprise type!");
            return;
        }
        if (!util.notNullOrEmpty(enterpriseName)) {
            JOptionPane.showMessageDialog(null, "Please enter an enterprise name.");
            return;
        } else if (!util.isValidName(enterpriseName)) {
            JOptionPane.showMessageDialog(null, "Please enter a valid enterprise name.");
            return;
        }
        List<Enterprise> enterpriseList = networkObj.getEnterpriseDirectory().getEnterpriseList();
        for (Enterprise enterpriseObj : enterpriseList) {
            if (enterpriseObj.getName().equalsIgnoreCase(enterpriseName)) {
                JOptionPane.showMessageDialog(null, "This enterprise already exists. Please create a new enterprise.");
                return;
            }
        }
        networkObj.getEnterpriseDirectory().createAndAddEnterprise(enterpriseName, enterpriseType);
        System.out.println("Successfully created new enterprise " +enterpriseName+ "of type " +enterpriseType);
        populateTable();
        enterpriseNameTxt.setText("");
    }//GEN-LAST:event_submitBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_backBtnActionPerformed

    private void cityDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityDropdownActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_cityDropdownActionPerformed

    private void enterpriseNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseNameTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox cityDropdown;
    private javax.swing.JLabel cityLbl;
    private javax.swing.JLabel enterpriseNameLbl;
    private javax.swing.JTextField enterpriseNameTxt;
    private javax.swing.JComboBox enterpriseTypeDropdown;
    private javax.swing.JLabel enterpriseTypeLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jscrollPane;
    private javax.swing.JTable manageEnterpriseTbl;
    private javax.swing.JLabel manageEnterprisesLbl;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
