/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Campaign;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FundingEnterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Entity.Applicant;
import Business.Entity.ApplicantDirectory;
import Business.Entity.CampaignEvent;
import Business.Network.Network;
import Business.Organization.ApplicantOrg;
import Business.Organization.CorporateFundOrg;
import Business.Organization.TrustFundOrg;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Utils.Utils;
import Business.WorkQueue.AwarenessWorkRequest;
import Business.WorkQueue.FundingWorkRequest;
import Business.WorkQueue.WorkRequest;
import UI.FundsRetrieval.FundsRequestStatusPanel;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aditi
 */
public class AwarenessCampaignInitiator extends javax.swing.JPanel {

    EcoSystem ecoSystem;
    JPanel panel;
    private Enterprise enterprise;
    private UserAccount userAccount;
    ApplicantDirectory appDirectory = new ApplicantDirectory();
    Utils utility;
    private DB4OUtil dB4OUtilObj = DB4OUtil.getInstance();
    /**
     * Creates new form AwarenessCampaignInitiator
     */
    public AwarenessCampaignInitiator(EcoSystem ecoSystem, JPanel panel, Enterprise enterprise, UserAccount userAccount) {
        
        initComponents();
        this.ecoSystem = ecoSystem;
        this.panel = panel;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        
        populateEventTable();
        populateNetworkList();
        populatecampTable();
    }
    
    public void populatecampTable(){
        DefaultTableModel dtm = (DefaultTableModel)awarenessCampRequestsDetailsTbl.getModel();
        dtm.setRowCount(0);
        
        for (Network network1 : ecoSystem.getNetworks()) {
            for (Enterprise enterprise : network1.getEnterpriseDirectory().getEnterpriseList()) {
                if(enterprise instanceof HospitalEnterprise){
                    for(WorkRequest wr : enterprise.getWorkQueue().getWorkRequestList()){
                        if (wr instanceof AwarenessWorkRequest) {
                        Object[] row = new Object[4];
                        
                        AwarenessWorkRequest req = (AwarenessWorkRequest)wr;
                        row[0] = wr;
                        row[1] = req.getOrgans();
                        row[2] = wr.getStatus();
                        row[3] = wr.getSender();
                
                        dtm.addRow(row);
                    }
                    }
                }
            }

        }

    }
    public void populateEventTable(){
        
        DefaultTableModel dtm = (DefaultTableModel)upcomingEventDetailsTbl.getModel();
        dtm.setRowCount(0);
        
        if(ecoSystem != null && ecoSystem.getCampaignList() != null){
            for(CampaignEvent campaign : ecoSystem.getCampaignList()){
                Object[] row = new Object[4];
                row[0] = campaign.getCampaignName();
                row[1] = campaign.getNetworkName();
                row[2] = campaign.getDate();
                row[3] = campaign.getMoney();
                
                dtm.addRow(row);
            }
            
        }
        dB4OUtilObj.storeSystem(ecoSystem);
    }
    
    public void populateNetworkList(){
        
        selectCityDropdown.removeAllItems();
        for(Network networkName : ecoSystem.getNetworks()){
            selectCityDropdown.addItem(networkName);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upcomingEventDetailsLbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        upcomingEventDetailsTbl = new javax.swing.JTable();
        selectCityLbl = new javax.swing.JLabel();
        selectCityDropdown = new javax.swing.JComboBox();
        eventDateLbl = new javax.swing.JLabel();
        setupEventTrustBtn = new javax.swing.JButton();
        eventNameFormLabel = new javax.swing.JLabel();
        eventNameTxt = new javax.swing.JTextField();
        requestFundsTxt = new javax.swing.JTextField();
        requestFundsLbl = new javax.swing.JLabel();
        requestFundsFormCurrencyLabel = new javax.swing.JLabel();
        fundsRequestStatusBtn = new javax.swing.JButton();
        eventdateTxt = new com.toedter.calendar.JDateChooser();
        setupEventCorporatesBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        awarenessCampRequestsDetailsTbl = new javax.swing.JTable();
        awarenessCampRequestsDetailsLbl = new javax.swing.JLabel();
        appointBtn = new javax.swing.JButton();
        approveBtn = new javax.swing.JButton();
        declineButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(null);

        upcomingEventDetailsLbl.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        upcomingEventDetailsLbl.setText("Upcoming Event Details");
        add(upcomingEventDetailsLbl);
        upcomingEventDetailsLbl.setBounds(420, 250, 300, 27);

        upcomingEventDetailsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Event Name", "Network", "Date", "Funds"
            }
        ));
        jScrollPane3.setViewportView(upcomingEventDetailsTbl);

        add(jScrollPane3);
        jScrollPane3.setBounds(90, 290, 949, 137);

        selectCityLbl.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        selectCityLbl.setText("Select City:");
        add(selectCityLbl);
        selectCityLbl.setBounds(70, 450, 150, 25);

        selectCityDropdown.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        selectCityDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectCityDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCityDropdownActionPerformed(evt);
            }
        });
        add(selectCityDropdown);
        selectCityDropdown.setBounds(250, 450, 170, 35);

        eventDateLbl.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        eventDateLbl.setText("Event Date:");
        add(eventDateLbl);
        eventDateLbl.setBounds(570, 450, 160, 25);

        setupEventTrustBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        setupEventTrustBtn.setText("Setup Event for Trust");
        setupEventTrustBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setupEventTrustBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setupEventTrustBtnActionPerformed(evt);
            }
        });
        add(setupEventTrustBtn);
        setupEventTrustBtn.setBounds(180, 580, 320, 50);

        eventNameFormLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        eventNameFormLabel.setText("Event Name:");
        add(eventNameFormLabel);
        eventNameFormLabel.setBounds(70, 510, 137, 25);

        eventNameTxt.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        eventNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventNameTxtActionPerformed(evt);
            }
        });
        add(eventNameTxt);
        eventNameTxt.setBounds(250, 510, 147, 35);

        requestFundsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestFundsTxtActionPerformed(evt);
            }
        });
        add(requestFundsTxt);
        requestFundsTxt.setBounds(780, 520, 180, 33);

        requestFundsLbl.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        requestFundsLbl.setText("Request Funds:");
        add(requestFundsLbl);
        requestFundsLbl.setBounds(570, 520, 180, 25);

        requestFundsFormCurrencyLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        requestFundsFormCurrencyLabel.setText("$");
        add(requestFundsFormCurrencyLabel);
        requestFundsFormCurrencyLabel.setBounds(720, 510, 18, 28);

        fundsRequestStatusBtn.setBackground(new java.awt.Color(153, 204, 255));
        fundsRequestStatusBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fundsRequestStatusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/process.png"))); // NOI18N
        fundsRequestStatusBtn.setText("Funds Reqested Status");
        fundsRequestStatusBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fundsRequestStatusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundsRequestStatusBtnActionPerformed(evt);
            }
        });
        add(fundsRequestStatusBtn);
        fundsRequestStatusBtn.setBounds(620, 640, 361, 50);
        add(eventdateTxt);
        eventdateTxt.setBounds(770, 450, 170, 32);

        setupEventCorporatesBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        setupEventCorporatesBtn.setText("Setup Event for Corporates");
        setupEventCorporatesBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setupEventCorporatesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setupEventCorporatesBtnActionPerformed(evt);
            }
        });
        add(setupEventCorporatesBtn);
        setupEventCorporatesBtn.setBounds(180, 640, 320, 50);

        awarenessCampRequestsDetailsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Organs", "Status", "Sender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(awarenessCampRequestsDetailsTbl);

        add(jScrollPane1);
        jScrollPane1.setBounds(100, 60, 950, 130);

        awarenessCampRequestsDetailsLbl.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        awarenessCampRequestsDetailsLbl.setText("Awareness Camp Requests Details by Hospital");
        add(awarenessCampRequestsDetailsLbl);
        awarenessCampRequestsDetailsLbl.setBounds(350, 10, 540, 40);

        appointBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        appointBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/icons8-audit-24.png"))); // NOI18N
        appointBtn.setText("Appoint to me");
        appointBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointBtnActionPerformed(evt);
            }
        });
        add(appointBtn);
        appointBtn.setBounds(120, 210, 200, 30);

        approveBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        approveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/check.png"))); // NOI18N
        approveBtn.setText("Approve");
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });
        add(approveBtn);
        approveBtn.setBounds(580, 200, 160, 30);

        declineButton3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        declineButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/close.png"))); // NOI18N
        declineButton3.setText("Decline");
        declineButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineButton3ActionPerformed(evt);
            }
        });
        add(declineButton3);
        declineButton3.setBounds(840, 200, 160, 30);
    }// </editor-fold>//GEN-END:initComponents

    //Method to check common validation for Trust and Corporate
    private boolean checkValidaion(Network networkName, String campaignName, Date eventDate){
        
        boolean value = true;
        
        Date date = new Date();
        Date today = new java.sql.Date (date.getTime());
 
        try{
        if(networkName.equals(null)){
            JOptionPane.showMessageDialog(null, "Please select city for the event");
            return false;
        }else if(campaignName.equals("")){
            JOptionPane.showMessageDialog(null, "Please add the event Name ");
            return false;
        }else if(eventDate.equals(null)){
            JOptionPane.showMessageDialog(null, "Please select the date for the event");
            return false;
        }else if(requestFundsTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter the amount of funds required");
            return false;
        }
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Please enter values for all the fields");
            return false;
        }
        /*
        if(!(utility.isValidCampaign(campaignName))){
            JOptionPane.showMessageDialog(null, "Campign Name is not valid");
            return;
        }*/
        
        //Validate Date
        try{
            if(eventDate.compareTo(today) < 0){
                JOptionPane.showMessageDialog(null,"Please select a valid date for the event");
               return false;
            }
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Please add the date");
            return false;
        }
        
        return value;
        //Handle exception for funds 
        
    }
    
    
    private void setupEventTrustBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setupEventTrustBtnActionPerformed

        Network networkName = (Network) selectCityDropdown.getSelectedItem();
        String campaignName = eventNameTxt.getText();
        Date eventDate = eventdateTxt.getDate();
        String money = requestFundsTxt.getText();
  
        Date date = new Date();
        Date today = new java.sql.Date (date.getTime());
 
        try{
        if(networkName.equals(null)){
            JOptionPane.showMessageDialog(null, "Please select city for the event");
            return;
        }else if(campaignName.equals("")){
            JOptionPane.showMessageDialog(null, "Please add the event Name ");
            return;
        }else if(eventDate.equals(null)){
            JOptionPane.showMessageDialog(null, "Please select the date for the event");
            return;
        }else if(requestFundsTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter the amount of funds required");
            return;
        }
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Please enter values for all the fields");
            return;
        }
        
        //Field validation for event name
       utility = new Utils();
       if(!utility.isValidName(campaignName)){
           JOptionPane.showMessageDialog(null, "Please enter valid name for the event");
            return;
       }
        /*
        if(!(utility.isValidCampaign(campaignName))){
            JOptionPane.showMessageDialog(null, "Campign Name is not valid");
            return;
        }*/
        
        //Validate Date
        try{
            if(eventDate.compareTo(today) < 0){
                JOptionPane.showMessageDialog(null,"Please select a valid date for the event");
               return;
            }
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Please select the date for the event");
            return;
        }
        
      
        //Handle exception for funds 
        
        float money1 = 0;
        try{
            money1 = Float.parseFloat(money);
            requestFundsTxt.setText("");
            
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Please add valid amount of funds");
                  return ; 
        }
        
        //Send email to all the applicants
        if(ecoSystem != null){
            for(Applicant applicant : appDirectory.getApplicantRecords()){
                utility.sendEmail(applicant.getApplicantEmailId(), campaignName, String.valueOf(eventDate), String.valueOf(networkName));
            }
            
            for(Network network: ecoSystem.getNetworks()){
                if(network.getName().equals(String.valueOf(networkName))){
                  for(Enterprise enterprise :   network.getEnterpriseDirectory().getEnterpriseList()){
                    for (Organization organisation : enterprise.getOrganizationDirectory().getOrganizationList()){
                        if(organisation instanceof ApplicantOrg){
                    }
                    }
                  }
                }
            }
        }
        
        FundingWorkRequest req = new FundingWorkRequest();
        req.setMessage("Kindly provide approval for the requested funds!!");
        req.setSender(userAccount);
        req.setStatus("Sent");
        req.setCampaign(eventNameTxt.getText());
        req.setAmount(money1);
        req.setEventName(campaignName);
        req.setFundType("Trust");

        
        Organization org1 = null;
         for(Network network : ecoSystem.getNetworks()){          
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                if(enterprise instanceof FundingEnterprise){
                   
                    for(Organization org :  enterprise.getOrganizationDirectory().getOrganizationList()){  
                        System.out.println(org.toString());
                       if(org instanceof TrustFundOrg){
                           org1 = org; 
                           System.out.println(org1.toString());
                       }
                   }
                }
            }
        }
        if(org1 != null){    
            org1.getWorkQueue().getWorkRequestList().add(req);
            userAccount.getWorkQueue().getWorkRequestList().add(req);
            System.out.println(org1.getWorkQueue().getWorkRequestList());
            System.out.println(userAccount.getWorkQueue().getWorkRequestList());
        }
        
        CampaignEvent campaign = ecoSystem.createCampaign();
        campaign.setCampaignName(campaignName);
        campaign.setNetworkName(networkName.getName());
        campaign.setDate(eventDate);
        campaign.setMoney(money1);
        
        JOptionPane.showMessageDialog(null, "Awareness event created successfully.");
        eventNameTxt.setText("");
        eventdateTxt.setDate(eventDate);
        requestFundsTxt.setText("");
        populateEventTable();
           
    }//GEN-LAST:event_setupEventTrustBtnActionPerformed

    private void requestFundsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestFundsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestFundsTxtActionPerformed

    private void fundsRequestStatusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundsRequestStatusBtnActionPerformed
        
        FundsRequestStatusPanel freqPanel = new FundsRequestStatusPanel(enterprise, panel, userAccount);
        panel.add("FundRequestStatusJPanel", freqPanel);
        CardLayout layout = (CardLayout) panel.getLayout();
        layout.next(panel);
    }//GEN-LAST:event_fundsRequestStatusBtnActionPerformed

    private void setupEventCorporatesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setupEventCorporatesBtnActionPerformed
        // TODO add your handling code here:
        Network networkName = (Network) selectCityDropdown.getSelectedItem();
        String campaignName = eventNameTxt.getText();
        Date eventDate = eventdateTxt.getDate();
        String money = requestFundsTxt.getText();
        
        //Validate fields
        Date date = new Date();
        Date today = new java.sql.Date (date.getTime());
 
        try{
        if(networkName.equals(null)){
            JOptionPane.showMessageDialog(null, "Please select city for the event");
            return;
        }else if(campaignName.equals("")){
            JOptionPane.showMessageDialog(null, "Please add the event Name ");
            return;
        }else if(eventDate.equals(null)){
            JOptionPane.showMessageDialog(null, "Please select the date for the event");
            return;
        }else if(requestFundsTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter the amount of funds required");
            return;
        }
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Please enter values for all the fields");
            return;
        }
        /*
        if(!(utility.isValidCampaign(campaignName))){
            JOptionPane.showMessageDialog(null, "Campign Name is not valid");
            return;
        }*/
        
        //Validate Date
        try{
            if(eventDate.compareTo(today) < 0){
                JOptionPane.showMessageDialog(null,"Please select a valid date for the event");
               return;
            }
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Please add the date");
            return;
        }
        
       
        //Handle exception for funds 
        
        //Check validation for funds
        float money1 = 0;
        try{
            money1 = Float.parseFloat(money);
            requestFundsTxt.setText("");
            
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Please add correct amount of funds");
                  return ; 
        }
        
        //Send email to all the applicants
        if(ecoSystem != null){
            System.out.println("####LP#### Befoer sending email");
            for(Applicant applicant : appDirectory.getApplicantRecords()){
                utility.sendEmail(applicant.getApplicantEmailId(), campaignName, String.valueOf(eventDate), String.valueOf(networkName));
            }
            
            for(Network network: ecoSystem.getNetworks()){
                if(network.getName().equals(String.valueOf(networkName))){
                  for(Enterprise enterprise :   network.getEnterpriseDirectory().getEnterpriseList()){
                    for (Organization organisation : enterprise.getOrganizationDirectory().getOrganizationList()){
                        if(organisation instanceof ApplicantOrg){
                           //LP Please add code later!!!
                    }
                    }
                  }
                }
            }
        }
        
        FundingWorkRequest req = new FundingWorkRequest();
        req.setMessage("Kindly provide approval for the requested funds!!");
        req.setSender(userAccount);
        req.setStatus("Sent");
        req.setCampaign(eventNameTxt.getText());
        req.setAmount(money1);
        req.setEventName(campaignName);
        req.setFundType("Corporate");

        
        Organization org1 = null;
         for(Network network : ecoSystem.getNetworks()){          
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                System.out.println("####LP#### Enterprise" +enterprise.toString());
                if(enterprise instanceof FundingEnterprise){
                   
                    for(Organization org :  enterprise.getOrganizationDirectory().getOrganizationList()){  
                        System.out.println("####LP####");
                        System.out.println(org.toString());
                       if(org instanceof CorporateFundOrg){
                           org1 = org; 
                           System.out.println("####LP####");
                           System.out.println(org1.toString());
                       }
                   }
                }
            }
        }
        if(org1 != null){
            System.out.println("####LP####");
            System.out.println(org1);
            
            org1.getWorkQueue().getWorkRequestList().add(req);
            userAccount.getWorkQueue().getWorkRequestList().add(req);
            System.out.println(org1.getWorkQueue().getWorkRequestList());
            System.out.println(userAccount.getWorkQueue().getWorkRequestList());
        }
        
        CampaignEvent campaign = ecoSystem.createCampaign();
        campaign.setCampaignName(campaignName);
        campaign.setNetworkName(networkName.getName());
        campaign.setDate(eventDate);
        campaign.setMoney(money1);
        
        JOptionPane.showMessageDialog(null, "Awareness event created successfully.");
        eventNameTxt.setText("");
        eventdateTxt.setDate(eventDate);
        requestFundsTxt.setText("");
        populateEventTable();
    }//GEN-LAST:event_setupEventCorporatesBtnActionPerformed

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
         // TODO add your handling code here:
         int selectedRow = awarenessCampRequestsDetailsTbl.getSelectedRow();

        if(awarenessCampRequestsDetailsTbl.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "No rows available to select", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        AwarenessWorkRequest request = (AwarenessWorkRequest)awarenessCampRequestsDetailsTbl.getValueAt(selectedRow, 0);
        if( request.getStatus().equalsIgnoreCase("Approved") || request.getStatus().equalsIgnoreCase("Declined")){
            JOptionPane.showMessageDialog(null, "The request has already been Approved/Declined", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }else if(request.getStatus().equalsIgnoreCase("Sent")){
            JOptionPane.showMessageDialog(null, "Please assign therequest first!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }else if(request.getStatus().equalsIgnoreCase("Assigned")){
           request.setStatus("Approved"); 
        JOptionPane.showMessageDialog(null, "The request has already been Approved successfully!");
        populatecampTable();
        }
        
    }//GEN-LAST:event_approveBtnActionPerformed

    private void appointBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = awarenessCampRequestsDetailsTbl.getSelectedRow();

        if(awarenessCampRequestsDetailsTbl.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "No rows available to select", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        AwarenessWorkRequest request = (AwarenessWorkRequest)awarenessCampRequestsDetailsTbl.getValueAt(selectedRow, 0);
        if(request.getStatus().equalsIgnoreCase("Assigned") ){
            JOptionPane.showMessageDialog(null, "The request has already been Assigned", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }else if(request.getStatus().equalsIgnoreCase("Approved") || request.getStatus().equalsIgnoreCase("Declined")){
            JOptionPane.showMessageDialog(null, "The request has already been Approved/Declined", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        request.setStatus("Assigned");
        JOptionPane.showMessageDialog(null, "The request has been Assigned successfully!!");
        populatecampTable();

    }//GEN-LAST:event_appointBtnActionPerformed

    private void declineButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = awarenessCampRequestsDetailsTbl.getSelectedRow();

        if(awarenessCampRequestsDetailsTbl.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "No rows available to select", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        AwarenessWorkRequest request = (AwarenessWorkRequest)awarenessCampRequestsDetailsTbl.getValueAt(selectedRow, 0);
        if( request.getStatus().equalsIgnoreCase("Approved") || request.getStatus().equalsIgnoreCase("Declined")){
            JOptionPane.showMessageDialog(null, "The request has already been Approved/Declined", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }else if(request.getStatus().equalsIgnoreCase("Sent")){
            JOptionPane.showMessageDialog(null, "Please assign the request first!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }else if(request.getStatus().equalsIgnoreCase("Assigned")){
           request.setStatus("Declined"); 
           JOptionPane.showMessageDialog(null, "The request has been Declined successfully!!");
        populatecampTable();
        }

    }//GEN-LAST:event_declineButton3ActionPerformed

    private void eventNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventNameTxtActionPerformed

    private void selectCityDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCityDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectCityDropdownActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointBtn;
    private javax.swing.JButton approveBtn;
    private javax.swing.JLabel awarenessCampRequestsDetailsLbl;
    private javax.swing.JTable awarenessCampRequestsDetailsTbl;
    private javax.swing.JButton declineButton3;
    private javax.swing.JLabel eventDateLbl;
    private javax.swing.JLabel eventNameFormLabel;
    private javax.swing.JTextField eventNameTxt;
    private com.toedter.calendar.JDateChooser eventdateTxt;
    private javax.swing.JButton fundsRequestStatusBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel requestFundsFormCurrencyLabel;
    private javax.swing.JLabel requestFundsLbl;
    private javax.swing.JTextField requestFundsTxt;
    private javax.swing.JComboBox selectCityDropdown;
    private javax.swing.JLabel selectCityLbl;
    private javax.swing.JButton setupEventCorporatesBtn;
    private javax.swing.JButton setupEventTrustBtn;
    private javax.swing.JLabel upcomingEventDetailsLbl;
    private javax.swing.JTable upcomingEventDetailsTbl;
    // End of variables declaration//GEN-END:variables
}
